[main]
name = "manjaro"
tag = ["zsh", "2022-12-16"]
os = "manjaro"
release = "stable"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "manjaro-zsh_amd64_2022-12-16_12-11.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "83b553537a92ef394c982695948b29bccacd2f3dc35a837522ff63bf2b9bed59"

# zstd: [1-22]
zstd-level = 20

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "1.1G"
tar_bytes = 1174274560

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "275M"
zstd_bytes = 287346066

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20221209"
previous_tag = "2022-12-09"
previous_file = "manjaro-zsh_amd64_2022-12-09_12-10-rootfs.tar.zst"
previous_sha256 = "ceec784b934111730544ac9850addd321fefc6f6bdcf2160077ef3ec6a25fdce"

current_version = "latest01"
current_date = "20221216"
old_file = "manjaro-zsh_amd64_2022-12-02_12-11-rootfs.tar.zst"
old_sha256 = "602ecc027630b4c334eacf0ee21d1df9464f6adc131ec1d065a40d7f51dfc0ac"
# edition 2021
# DISTRO_NAME=manjaro-stable_amd64
# ROOTFS_FILE=manjaro-zsh_amd64_2022-12-16_12-11-rootfs.tar.zst
# SHA256SUM=83b553537a92ef394c982695948b29bccacd2f3dc35a837522ff63bf2b9bed59
# BUILD_DATE=20221216
# BUILD_TAG=2022-12-16
# STATUS=completed
# VERSION=latest01
# END_TIME=12:11

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-12-16
begin = 2022-12-16 12:02:24.692949921+00:00
start-sync_0 = 12:04:58
start-zstd = 12:06:43
start-sync_1 = 12:10:59
end-sync_1 = 12:11:22
end = 2022-12-16 12:11:22.555861104+00:00

[server]
repo = "cake233/manjaro-zsh-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (GNU libc) 2.36'
zsh = 'zsh 5.9 (x86_64-pc-linux-gnu)'
