[main]
name = "alpine"
tag = ["xfce", "2023-02-16"]
os = "alpine"
release = "edge"
arch = "arm64"
platform = "linux/arm64"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "alpine-xfce_arm64_2023-02-16_00-26.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "132f8fd5adfe156dd2cb238bf360766c902b7975a362cc6ff2558b35f6011775"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "1017M"
tar_bytes = 1065679360

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "331M"
zstd_bytes = 346398816

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20230209"
previous_tag = "2023-02-09"
previous_file = "alpine-xfce_arm64_2023-02-09_00-17-rootfs.tar.zst"
previous_sha256 = "b9692b92e55e74b3281614fc4ddb3ab6e183d5aa55d95f307a6272fc5f2e4b55"

current_version = "latest01"
current_date = "20230216"
old_file = "alpine-xfce_arm64_2023-02-02_00-14-rootfs.tar.zst"
old_sha256 = "37c4cf4cd911c97593f824220609a2b7f2e9dc034841044a75d3cd2b78b9e800"
# edition 2021
# DISTRO_NAME=alpine-edge_arm64
# ROOTFS_FILE=alpine-xfce_arm64_2023-02-16_00-26-rootfs.tar.zst
# SHA256SUM=132f8fd5adfe156dd2cb238bf360766c902b7975a362cc6ff2558b35f6011775
# BUILD_DATE=20230216
# BUILD_TAG=2023-02-16
# STATUS=completed
# VERSION=latest01
# END_TIME=00:26

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-02-16
begin = 2023-02-16 00:07:14.665257277+00:00
start-sync_0 = 00:21:49
start-zstd = 00:22:49
start-sync_1 = 00:26:14
end-sync_1 = 00:26:49
end = 2023-02-16 00:26:49.119377402+00:00

[server]
repo = "cake233/alpine-xfce-arm64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
start_sync = 2023-02-16 06:14:25.910372444+00:00
end_sync = 2023-02-16 06:15:30.713885296+00:00
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "C.UTF-8"

[version]
ldd = 'musl libc (aarch64) Version 1.2.3'
zsh = 'zsh 5.9 (aarch64-alpine-linux-musl)'

[port]
tcp = [5902, 36080]
