[main]
name = "alpine"
tag = ["mate", "2023-09-21"]
os = "alpine"
release = "edge"
arch = "arm64"
platform = "linux/arm64"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "alpine-mate_arm64_2023-09-21_00-16.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "95063f16b115e3e8791fecbe81e7fa61b7d2ea5fec19d52c905d3090c17527d8"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "1.3G"
tar_bytes = 1298115072

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "375M"
zstd_bytes = 392862269

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20211128"
previous_tag = ""
previous_file = ""
previous_sha256 = ""

current_version = "latest01"
current_date = "20230921"
old_file = ""
old_sha256 = ""
# edition 2021
# DISTRO_NAME=alpine-edge_arm64
# ROOTFS_FILE=alpine-mate_arm64_2023-09-21_00-16-rootfs.tar.zst
# SHA256SUM=95063f16b115e3e8791fecbe81e7fa61b7d2ea5fec19d52c905d3090c17527d8
# BUILD_DATE=20230921
# BUILD_TAG=2023-09-21
# STATUS=completed
# VERSION=latest01
# END_TIME=00:16

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-09-21
begin = 2023-09-21 00:08:06.942555574+00:00
start-sync_0 = 00:11:01
start-zstd = 00:11:59
start-sync_1 = 00:16:10
end-sync_1 = 00:16:40
end = 2023-09-21 00:16:40.726759046+00:00

[server]
repo = "cake233/alpine-mate-arm64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
start_sync = 2023-09-21 06:10:55.566118659+00:00
end_sync = 2023-09-21 06:12:01.706886073+00:00
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "C.UTF-8"

[version]
ldd = 'musl libc (aarch64) Version 1.2.4_git20230717'
zsh = 'zsh 5.9 (aarch64-alpine-linux-musl)'

[port]
tcp = [5902, 36080]
