[main]
name = "alpine"
tag = ["mate", "2023-08-31"]
os = "alpine"
release = "edge"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "alpine-mate_amd64_2023-08-31_00-16.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "9e5143ac7d458d35705cfc5408c4804fe92e514b3f9a7010c069b33bede52954"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "1.2G"
tar_bytes = 1276175872

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "384M"
zstd_bytes = 402590134

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20230824"
previous_tag = "2023-08-24"
previous_file = "alpine-mate_amd64_2023-08-24_00-16-rootfs.tar.zst"
previous_sha256 = "f7e1f48864ccad9016905773bfad454fe21e6edb46a4955ce2cf4a2af3ab7f8b"

current_version = "latest02"
current_date = "20230831"
old_file = "alpine-mate_amd64_2023-08-17_00-15-rootfs.tar.zst"
old_sha256 = "f9606f33815e2f6543bbd3823820fe93aa5daa80402c8c4dea6092b661e28e3a"
# edition 2021
# DISTRO_NAME=alpine-edge_amd64
# ROOTFS_FILE=alpine-mate_amd64_2023-08-31_00-16-rootfs.tar.zst
# SHA256SUM=9e5143ac7d458d35705cfc5408c4804fe92e514b3f9a7010c069b33bede52954
# BUILD_DATE=20230831
# BUILD_TAG=2023-08-31
# STATUS=completed
# VERSION=latest02
# END_TIME=00:16

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-08-31
begin = 2023-08-31 00:08:02.797100138+00:00
start-sync_0 = 00:09:52
start-zstd = 00:11:04
start-sync_1 = 00:16:10
end-sync_1 = 00:16:48
end = 2023-08-31 00:16:48.357492562+00:00

[server]
repo = "cake233/alpine-mate-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = true
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "C.UTF-8"

[version]
ldd = 'musl libc (x86_64) Version 1.2.4_git20230717'
zsh = 'zsh 5.9 (x86_64-alpine-linux-musl)'

[port]
tcp = [5902, 36080]
