[main]
name = "alpine"
tag = ["kde", "2023-12-07"]
os = "alpine"
release = "edge"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "alpine-kde_amd64_2023-12-07_00-11.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "a6b03d7fe83f4e85e6180da805d978b4ecc1e01f8530e5c89c7df9f2a95d9d99"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "916M"
tar_bytes = 959473664

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "307M"
zstd_bytes = 321610526

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20231123"
previous_tag = "2023-11-23"
previous_file = "alpine-kde_amd64_2023-11-23_00-12-rootfs.tar.zst"
previous_sha256 = "cd496874c1911e593d85b3867b0608af0a06cb1803f8bda37a482fa5acc10a80"

current_version = "latest02"
current_date = "20231207"
old_file = "alpine-kde_amd64_2023-11-16_00-11-rootfs.tar.zst"
old_sha256 = "7843b56cf30b20d57482c9322f1d7d01d61b3b01950b78eebd7c5d518943df73"
# edition 2021
# DISTRO_NAME=alpine-edge_amd64
# ROOTFS_FILE=alpine-kde_amd64_2023-12-07_00-11-rootfs.tar.zst
# SHA256SUM=a6b03d7fe83f4e85e6180da805d978b4ecc1e01f8530e5c89c7df9f2a95d9d99
# BUILD_DATE=20231207
# BUILD_TAG=2023-12-07
# STATUS=completed
# VERSION=latest02
# END_TIME=00:11

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-12-07
begin = 2023-12-07 00:06:22.686629147+00:00
start-sync_0 = 00:07:17
start-zstd = 00:07:53
start-sync_1 = 00:10:50
end-sync_1 = 00:11:14
end = 2023-12-07 00:11:14.129695108+00:00

[server]
repo = "cake233/alpine-kde-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = true
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "C.UTF-8"

[version]
ldd = 'musl libc (x86_64) Version 1.2.4_git20230717'
zsh = 'zsh 5.9 (x86_64-alpine-linux-musl)'

[port]
tcp = [5902, 36080]
