[main]
name = "alpine"
tag = ["zsh", "2023-03-02"]
os = "alpine"
release = "edge"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "alpine-zsh_amd64_2023-03-02_00-05.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "2cdd987c3d288ec61c3e549e0e28ea6c1cc084348f219bb2e5f40d86b0d9eea7"

# zstd: [1-22]
zstd-level = 20

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "96M"
tar_bytes = 100054528

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "31M"
zstd_bytes = 32439221

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20230223"
previous_tag = "2023-02-23"
previous_file = "alpine-zsh_amd64_2023-02-23_00-05-rootfs.tar.zst"
previous_sha256 = "e875db1c8a82167d37c95c2df3b1619ed4b4f77b9e22214962aefc4556cda787"

current_version = "latest02"
current_date = "20230302"
old_file = "alpine-zsh_amd64_2023-02-16_00-05-rootfs.tar.zst"
old_sha256 = "946b6a57134234fb5edd55f9b43c69211f9f5cef20b1e5f5d9190f5db245363b"
# edition 2021
# DISTRO_NAME=alpine-edge_amd64
# ROOTFS_FILE=alpine-zsh_amd64_2023-03-02_00-05-rootfs.tar.zst
# SHA256SUM=2cdd987c3d288ec61c3e549e0e28ea6c1cc084348f219bb2e5f40d86b0d9eea7
# BUILD_DATE=20230302
# BUILD_TAG=2023-03-02
# STATUS=completed
# VERSION=latest02
# END_TIME=00:05

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-03-02
begin = 2023-03-02 00:02:28.451811174+00:00
start-sync_0 = 00:03:10
start-zstd = 00:04:34
start-sync_1 = 00:05:07
end-sync_1 = 00:05:17
end = 2023-03-02 00:05:17.431144332+00:00

[server]
repo = "cake233/alpine-zsh-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "C.UTF-8"

[version]
ldd = 'musl libc (x86_64) Version 1.2.3'
zsh = 'zsh 5.9 (x86_64-alpine-linux-musl)'
