[main]
name = "alpine"
tag = ["zsh", "2023-06-22"]
os = "alpine"
release = "edge"
arch = "i386"
platform = "linux/386"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "alpine-zsh_i386_2023-06-22_00-05.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "021f6e0a5602472c45c6438bd5996c13d4ff2b9bf7c5d927890e56195b6c0cd2"

# zstd: [1-22]
zstd-level = 20

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "93M"
tar_bytes = 97203200

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "31M"
zstd_bytes = 32481469

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20230615"
previous_tag = "2023-06-15"
previous_file = "alpine-zsh_i386_2023-06-15_00-06-rootfs.tar.zst"
previous_sha256 = "b297775e058fb2fc5dcec3ea729b73da4b992e5b9b9bdd7ad078eec5ca91fa83"

current_version = "latest01"
current_date = "20230622"
old_file = "alpine-zsh_i386_2023-06-08_00-05-rootfs.tar.zst"
old_sha256 = "216c9f82eed7c6de7e984a374cf5b86874618e2ed061b2df5ae011873888a140"
# edition 2021
# DISTRO_NAME=alpine-edge_i386
# ROOTFS_FILE=alpine-zsh_i386_2023-06-22_00-05-rootfs.tar.zst
# SHA256SUM=021f6e0a5602472c45c6438bd5996c13d4ff2b9bf7c5d927890e56195b6c0cd2
# BUILD_DATE=20230622
# BUILD_TAG=2023-06-22
# STATUS=completed
# VERSION=latest01
# END_TIME=00:05

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-06-22
begin = 2023-06-22 00:02:29.129055871+00:00
start-sync_0 = 00:03:57
start-zstd = 00:05:18
start-sync_1 = 00:05:49
end-sync_1 = 00:05:57
end = 2023-06-22 00:05:57.127665323+00:00

[server]
repo = "cake233/alpine-zsh-386"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = true
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "C.UTF-8"

[version]
ldd = 'musl libc (i386) Version 1.2.4'
zsh = 'zsh 5.9 (i586-alpine-linux-musl)'
