[main]
name = "alpine"
tag = ["mate", "2023-02-23"]
os = "alpine"
release = "edge"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "alpine-mate_amd64_2023-02-23_00-15.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "8af9170f78165f74d4fb219f29a829c476d2232c107b03441cbfb272f0b4f9cc"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "1.1G"
tar_bytes = 1132939264

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "340M"
zstd_bytes = 355552040

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20230216"
previous_tag = "2023-02-16"
previous_file = "alpine-mate_amd64_2023-02-16_00-13-rootfs.tar.zst"
previous_sha256 = "89ff049c75be2241ab63007d282c665e0cd3298c7fe37d551b3dfe846b41850e"

current_version = "latest02"
current_date = "20230223"
old_file = "alpine-mate_amd64_2023-02-09_00-13-rootfs.tar.zst"
old_sha256 = "9ac56fc07cdf9e861b913b11520cc95cc58c6ccd24350b542aa9dfb118d3de5e"
# edition 2021
# DISTRO_NAME=alpine-edge_amd64
# ROOTFS_FILE=alpine-mate_amd64_2023-02-23_00-15-rootfs.tar.zst
# SHA256SUM=8af9170f78165f74d4fb219f29a829c476d2232c107b03441cbfb272f0b4f9cc
# BUILD_DATE=20230223
# BUILD_TAG=2023-02-23
# STATUS=completed
# VERSION=latest02
# END_TIME=00:15

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-02-23
begin = 2023-02-23 00:07:14.298084672+00:00
start-sync_0 = 00:09:16
start-zstd = 00:10:22
start-sync_1 = 00:14:29
end-sync_1 = 00:15:00
end = 2023-02-23 00:15:00.127217167+00:00

[server]
repo = "cake233/alpine-mate-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = true
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "C.UTF-8"

[version]
ldd = 'musl libc (x86_64) Version 1.2.3'
zsh = 'zsh 5.9 (x86_64-alpine-linux-musl)'

[port]
tcp = [5902, 36080]
