[main]
name = "alpine"
tag = ["zsh", "2023-02-09"]
os = "alpine"
release = "edge"
arch = "arm64"
platform = "linux/arm64"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "alpine-zsh_arm64_2023-02-09_00-06.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "c50e292f3ef64b80d21859ec7be3a08d48bca2e23c664264bfdc25fff565d18f"

# zstd: [1-22]
zstd-level = 20

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "109M"
tar_bytes = 113647616

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "31M"
zstd_bytes = 32026814

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20230202"
previous_tag = "2023-02-02"
previous_file = "alpine-zsh_arm64_2023-02-02_00-06-rootfs.tar.zst"
previous_sha256 = "3c540448b9e6be9f0d6e3ab4fc5cd82b151644e9286b54cfe5cdc596c86aa37c"

current_version = "latest02"
current_date = "20230209"
old_file = "alpine-zsh_arm64_2023-01-26_00-05-rootfs.tar.zst"
old_sha256 = "7b332cf68beff1fce4e173ea2651cc3add22dda91e27a6481ceb90400f269eaf"
# edition 2021
# DISTRO_NAME=alpine-edge_arm64
# ROOTFS_FILE=alpine-zsh_arm64_2023-02-09_00-06-rootfs.tar.zst
# SHA256SUM=c50e292f3ef64b80d21859ec7be3a08d48bca2e23c664264bfdc25fff565d18f
# BUILD_DATE=20230209
# BUILD_TAG=2023-02-09
# STATUS=completed
# VERSION=latest02
# END_TIME=00:06

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-02-09
begin = 2023-02-09 00:02:25.010480983+00:00
start-sync_0 = 00:04:09
start-zstd = 00:05:33
start-sync_1 = 00:06:08
end-sync_1 = 00:06:14
end = 2023-02-09 00:06:14.761799286+00:00

[server]
repo = "cake233/alpine-zsh-arm64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = true
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "C.UTF-8"

[version]
ldd = 'musl libc (aarch64) Version 1.2.3'
zsh = 'zsh 5.9 (aarch64-alpine-linux-musl)'
