[main]
name = "kali"
tag = ["xfce", "2023-09-14"]
os = "kali"
release = "rolling"
arch = "arm64"
platform = "linux/arm64"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "kali-xfce_arm64_2023-09-14_13-41.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "bd6b391926497cc7a53f53ce9d34682c4d88aea244ef33eb9bde27ff6208f1c7"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "5.0G"
tar_bytes = 5323237376

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "1.4G"
zstd_bytes = 1469580078

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20230907"
previous_tag = "2023-09-07"
previous_file = "kali-xfce_arm64_2023-09-07_13-31-rootfs.tar.zst"
previous_sha256 = "8992f5a2c73fb0fd756ef41b7168e870f6ff8e5b8339e35e0e39c9e6dbf174c4"

current_version = "latest01"
current_date = "20230914"
old_file = "kali-xfce_arm64_2023-08-31_13-45-rootfs.tar.zst"
old_sha256 = "78405cd1a21af3532a3be5033b7ebd9be58a2870d71e4b7d56788ef598f5187f"
# edition 2021
# DISTRO_NAME=kali-rolling_arm64
# ROOTFS_FILE=kali-xfce_arm64_2023-09-14_13-41-rootfs.tar.zst
# SHA256SUM=bd6b391926497cc7a53f53ce9d34682c4d88aea244ef33eb9bde27ff6208f1c7
# BUILD_DATE=20230914
# BUILD_TAG=2023-09-14
# STATUS=completed
# VERSION=latest01
# END_TIME=13:41

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-09-14
begin = 2023-09-14 12:29:03.004278102+00:00
start-sync_0 = 13:17:12
start-zstd = 13:21:15
start-sync_1 = 13:39:32
end-sync_1 = 13:41:01
end = 2023-09-14 13:41:01.971365042+00:00

[server]
repo = "cake233/kali-xfce-arm64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
start_sync = 2023-09-14 18:14:56.266159977+00:00
end_sync = 2023-09-14 18:18:32.184469382+00:00
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (Debian GLIBC 2.37-7) 2.37'
zsh = 'zsh 5.9 (aarch64-unknown-linux-gnu)'

[port]
tcp = [5902, 36080]
