[main]
name = "ubuntu"
tag = ["kde", "2023-06-27", "devel"]
os = "ubuntu"
release = "dev"
arch = "armhf"
platform = "linux/arm/v7"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "ubuntu-kde_armhf_2023-06-27_00-53.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "66649c6d45753f2b564e82c1dfca2dbe10f52caf29770d4e253bf4a38af3dc73"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "3.8G"
tar_bytes = 4046478336

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "1.2G"
zstd_bytes = 1232010293

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20230620"
previous_tag = "2023-06-20"
previous_file = "ubuntu-kde_armhf_2023-06-20_01-01-rootfs.tar.zst"
previous_sha256 = "35d37484435a0a190190c28eda91fbd3ab1eaef54af5d037a5828885ebe54320"

current_version = "latest02"
current_date = "20230627"
old_file = "ubuntu-kde_armhf_2023-06-06_00-52-rootfs.tar.zst"
old_sha256 = "94b8ebbb15b7f9fca20e7c4070eddfba47d89927840c357a2c05f304894afb2d"
# edition 2021
# DISTRO_NAME=ubuntu-dev_armhf
# ROOTFS_FILE=ubuntu-kde_armhf_2023-06-27_00-53-rootfs.tar.zst
# SHA256SUM=66649c6d45753f2b564e82c1dfca2dbe10f52caf29770d4e253bf4a38af3dc73
# BUILD_DATE=20230627
# BUILD_TAG=2023-06-27
# STATUS=completed
# VERSION=latest02
# END_TIME=00:53

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-06-27
begin = 2023-06-27 00:02:55.237291148+00:00
start-sync_0 = 00:35:47
start-zstd = 00:38:54
start-sync_1 = 00:51:45
end-sync_1 = 00:53:00
end = 2023-06-27 00:53:00.931631710+00:00

[server]
repo = "cake233/ubuntu-kde-armv7"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (Ubuntu GLIBC 2.36-0ubuntu4) 2.36'
zsh = 'zsh 5.9 (arm-unknown-linux-gnueabihf)'

[port]
tcp = [5902, 36080]
