[main]
name = "ubuntu"
tag = ["kde", "2023-02-28", "devel"]
os = "ubuntu"
release = "dev"
arch = "arm64"
platform = "linux/arm64"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "ubuntu-kde_arm64_2023-02-28_01-05.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "89d52d444b0400ee022a1d1ae4b1165f6923d8c98b2418c67e06347d0a2b42a3"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "4.8G"
tar_bytes = 5052640256

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "1.3G"
zstd_bytes = 1377897266

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20230221"
previous_tag = "2023-02-21"
previous_file = "ubuntu-kde_arm64_2023-02-21_01-08-rootfs.tar.zst"
previous_sha256 = "8a9d5af87d7c10037895945afd43ff01fb0468d5c7ccb3bb53279b11a80af40c"

current_version = "latest01"
current_date = "20230228"
old_file = "ubuntu-kde_arm64_2023-02-14_01-04-rootfs.tar.zst"
old_sha256 = "3df59809790a31a9fe1ecc1681a4f2c79cb64e77a96c91789c21c4836df70087"
# edition 2021
# DISTRO_NAME=ubuntu-dev_arm64
# ROOTFS_FILE=ubuntu-kde_arm64_2023-02-28_01-05-rootfs.tar.zst
# SHA256SUM=89d52d444b0400ee022a1d1ae4b1165f6923d8c98b2418c67e06347d0a2b42a3
# BUILD_DATE=20230228
# BUILD_TAG=2023-02-28
# STATUS=completed
# VERSION=latest01
# END_TIME=01:05

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-02-28
begin = 2023-02-28 00:02:58.500614347+00:00
start-sync_0 = 00:43:06
start-zstd = 00:47:59
start-sync_1 = 01:04:08
end-sync_1 = 01:05:29
end = 2023-02-28 01:05:29.837734253+00:00

[server]
repo = "cake233/ubuntu-kde-arm64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (Ubuntu GLIBC 2.36-0ubuntu4) 2.36'
zsh = 'zsh 5.9 (aarch64-unknown-linux-gnu)'

[port]
tcp = [5902, 36080]
