[main]
name = "ubuntu"
tag = ["xfce", "2022-07-12", "devel"]
os = "ubuntu"
release = "dev"
arch = "arm64"
platform = "linux/arm64"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "ubuntu-xfce_arm64_2022-07-12_01-05.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "5541a5398f5d6ab4a19001d6848675c224c26c0b1cae948c7a3144d41776c44f"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "3.5G"
tar_bytes = 3715949568

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "983M"
zstd_bytes = 1030521132

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20220705"
previous_tag = "2022-07-05"
previous_file = "ubuntu-xfce_arm64_2022-07-05_01-02-rootfs.tar.zst"
previous_sha256 = "bc58e582fae8c1c11c1e1281518c963cb47599ab04634bb8a602d206b7ed79b3"

current_version = "latest02"
current_date = "20220712"
old_file = "ubuntu-xfce_arm64_2022-06-28_01-11-rootfs.tar.zst"
old_sha256 = "865fba8e71367fbca4a9c436119300bb682b3cafde3e1189545c51e6e25061d7"
# edition 2021
# DISTRO_NAME=ubuntu-dev_arm64
# ROOTFS_FILE=ubuntu-xfce_arm64_2022-07-12_01-05-rootfs.tar.zst
# SHA256SUM=5541a5398f5d6ab4a19001d6848675c224c26c0b1cae948c7a3144d41776c44f
# BUILD_DATE=20220712
# BUILD_TAG=2022-07-12
# STATUS=completed
# VERSION=latest02
# END_TIME=01:05

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-07-12
begin = 2022-07-12 00:20:31.592391206+00:00
start-sync_0 = 00:49:38
start-zstd = 00:52:31
start-sync_1 = 01:04:52
end-sync_1 = 01:05:54
end = 2022-07-12 01:05:54.681266797+00:00

[server]
repo = "cake233/ubuntu-xfce-arm64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (Ubuntu GLIBC 2.35-0ubuntu3) 2.35'
zsh = 'zsh 5.9 (aarch64-unknown-linux-gnu)'

[port]
tcp = [5902, 36080]
