[main]
name = "ubuntu"
tag = ["zsh", "2022-04-19", "devel"]
os = "ubuntu"
release = "dev"
arch = "armhf"
platform = "linux/arm/v7"
x11_or_wayland = false
syntax_version = "0.0.0-alpha.3"

[file]
name = "ubuntu-zsh_armhf_2022-04-19_00-19.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "cde394082c84fbee0da5cf7993512129de30fbfb789afba5d4c9e3e418e3630a"

# zstd: [1-22]
zstd-level = 20

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "574M"
tar_bytes = 601479680

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "109M"
zstd_bytes = 113395982

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20220411"
previous_tag = "2022-04-11"
previous_file = "ubuntu-zsh_armhf_2022-04-11_23-17-rootfs.tar.zst"
previous_sha256 = "54c393f99fef4e1d63dcec57d231bcbfdc11eafb83b9caf0e1eb8ca01c1f246f"

current_version = "latest01"
current_date = "20220419"
old_file = "ubuntu-zsh_armhf_2022-04-04_23-16-rootfs.tar.zst"
old_sha256 = "4a33db3d517f48061ed8560cbe6c3237ac6f771cf625d15f2e3f7049a2104a4c"
# edition 2021
# DISTRO_NAME=ubuntu-dev_armhf
# ROOTFS_FILE=ubuntu-zsh_armhf_2022-04-19_00-19-rootfs.tar.zst
# SHA256SUM=cde394082c84fbee0da5cf7993512129de30fbfb789afba5d4c9e3e418e3630a
# BUILD_DATE=20220419
# BUILD_TAG=2022-04-19
# STATUS=completed
# VERSION=latest01
# END_TIME=00:19

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-04-19
begin = 2022-04-19 00:02:21.341071733+00:00
start-sync_0 = 00:15:43
start-zstd = 00:17:28
start-sync_1 = 00:19:28
end-sync_1 = 00:19:41
end = 2022-04-19 00:19:41.244337932+00:00

[server]
repo = "cake233/ubuntu-zsh-armv7"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = false
previous = true
in_sync = true
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (Ubuntu GLIBC 2.35-0ubuntu3) 2.35'
zsh = 'zsh 5.8.1 (arm-unknown-linux-gnueabihf)'
