[main]
name = "ubuntu"
tag = ["lxqt", "2022-12-27", "devel"]
os = "ubuntu"
release = "dev"
arch = "arm64"
platform = "linux/arm64"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "ubuntu-lxqt_arm64_2022-12-27_01-15.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "bdf91a4fd554bf7f99dac22b2a062d0b4d01b33f6e7a5211f295406036d496a9"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "4.0G"
tar_bytes = 4244973568

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "1.1G"
zstd_bytes = 1149489503

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20221220"
previous_tag = "2022-12-20"
previous_file = "ubuntu-lxqt_arm64_2022-12-20_02-50-rootfs.tar.zst"
previous_sha256 = "bde3b53c30b556ff329fbb51a0690a29abcfebd97bd44c07eb016ae3e78f2289"

current_version = "latest02"
current_date = "20221227"
old_file = "ubuntu-lxqt_arm64_2022-12-13_01-03-rootfs.tar.zst"
old_sha256 = "9743d7c8b6d5631a9682a55bc3109b2bd97333a199080d4ac488562a6f0b3b1a"
# edition 2021
# DISTRO_NAME=ubuntu-dev_arm64
# ROOTFS_FILE=ubuntu-lxqt_arm64_2022-12-27_01-15-rootfs.tar.zst
# SHA256SUM=bdf91a4fd554bf7f99dac22b2a062d0b4d01b33f6e7a5211f295406036d496a9
# BUILD_DATE=20221227
# BUILD_TAG=2022-12-27
# STATUS=completed
# VERSION=latest02
# END_TIME=01:15

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-12-27
begin = 2022-12-27 00:02:57.571363008+00:00
start-sync_0 = 00:49:56
start-zstd = 00:54:10
start-sync_1 = 01:14:03
end-sync_1 = 01:15:24
end = 2022-12-27 01:15:24.533637882+00:00

[server]
repo = "cake233/ubuntu-lxqt-arm64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = true
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (Ubuntu GLIBC 2.36-0ubuntu4) 2.36'
zsh = 'zsh 5.9 (aarch64-unknown-linux-gnu)'

[port]
tcp = [5902, 36080]
