[main]
name = "ubuntu"
tag = ["kde", "2023-10-17", "devel"]
os = "ubuntu"
release = "dev"
arch = "arm64"
platform = "linux/arm64"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "ubuntu-kde_arm64_2023-10-17_02-17.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "cf38e790821a746f3530e29b57200425a26335e60a6436133e7de11503f0f8d3"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "5.3G"
tar_bytes = 5669541376

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "1.5G"
zstd_bytes = 1539151413

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20231010"
previous_tag = "2023-10-10"
previous_file = "ubuntu-kde_arm64_2023-10-10_02-15-rootfs.tar.zst"
previous_sha256 = "3c1e137345226fb9697e69da3af46afca73bc18dad90bf322ee8e80779f00751"

current_version = "latest02"
current_date = "20231017"
old_file = "ubuntu-kde_arm64_2023-10-03_01-48-rootfs.tar.zst"
old_sha256 = "6e364b198816d2d102050ab575c3bf267fcc528f81d4f868886403e786ac2f5a"
# edition 2021
# DISTRO_NAME=ubuntu-dev_arm64
# ROOTFS_FILE=ubuntu-kde_arm64_2023-10-17_02-17-rootfs.tar.zst
# SHA256SUM=cf38e790821a746f3530e29b57200425a26335e60a6436133e7de11503f0f8d3
# BUILD_DATE=20231017
# BUILD_TAG=2023-10-17
# STATUS=completed
# VERSION=latest02
# END_TIME=02:17

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-10-17
begin = 2023-10-17 00:33:54.272555005+00:00
start-sync_0 = 01:46:56
start-zstd = 01:52:47
start-sync_1 = 02:16:14
end-sync_1 = 02:17:57
end = 2023-10-17 02:17:57.874053044+00:00

[server]
repo = "cake233/ubuntu-kde-arm64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (Ubuntu GLIBC 2.38-1ubuntu6) 2.38'
zsh = 'zsh 5.9 (aarch64-unknown-linux-gnu)'

[port]
tcp = [5902, 36080]
