[main]
name = "ubuntu"
tag = ["lxqt", "2023-02-28", "devel"]
os = "ubuntu"
release = "dev"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "ubuntu-lxqt_amd64_2023-02-28_00-29.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "b9beed3c8d93f116de547d22fbd2e5bdf4e1a2702095c96f40eaa1cdb341ca8b"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "3.8G"
tar_bytes = 4008624640

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "1.1G"
zstd_bytes = 1082254829

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20230221"
previous_tag = "2023-02-21"
previous_file = "ubuntu-lxqt_amd64_2023-02-21_00-29-rootfs.tar.zst"
previous_sha256 = "86db36fa06d47c43cab69a3505c4b05ea7383abc97bffdff3e04331a519c72e5"

current_version = "latest01"
current_date = "20230228"
old_file = "ubuntu-lxqt_amd64_2023-02-14_00-27-rootfs.tar.zst"
old_sha256 = "bb2c614773143b64a8bca794c34a672097d20bb7f2c4c337e168470bf8ced3ba"
# edition 2021
# DISTRO_NAME=ubuntu-dev_amd64
# ROOTFS_FILE=ubuntu-lxqt_amd64_2023-02-28_00-29-rootfs.tar.zst
# SHA256SUM=b9beed3c8d93f116de547d22fbd2e5bdf4e1a2702095c96f40eaa1cdb341ca8b
# BUILD_DATE=20230228
# BUILD_TAG=2023-02-28
# STATUS=completed
# VERSION=latest01
# END_TIME=00:29

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-02-28
begin = 2023-02-28 00:02:58.530247408+00:00
start-sync_0 = 00:10:31
start-zstd = 00:14:02
start-sync_1 = 00:28:06
end-sync_1 = 00:29:11
end = 2023-02-28 00:29:11.148680523+00:00

[server]
repo = "cake233/ubuntu-lxqt-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (Ubuntu GLIBC 2.36-0ubuntu4) 2.36'
zsh = 'zsh 5.9 (x86_64-ubuntu-linux-gnu)'

[port]
tcp = [5902, 36080]
