[main]
name = "ubuntu"
tag = ["kde", "2022-06-21", "devel"]
os = "ubuntu"
release = "dev"
arch = "armhf"
platform = "linux/arm/v7"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "ubuntu-kde_armhf_2022-06-21_01-12.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "ad2cf4a16e2710f4dfe816d26ebc93c4f90e2644c336c3a14822b324e25e193c"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "3.4G"
tar_bytes = 3566457344

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "1.1G"
zstd_bytes = 1129041591

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20220614"
previous_tag = "2022-06-14"
previous_file = "ubuntu-kde_armhf_2022-06-14_01-13-rootfs.tar.zst"
previous_sha256 = "382d99e9b45b164d8718e8a4476fa5526ae1bc5984af3f90a802fc8491778769"

current_version = "latest01"
current_date = "20220621"
old_file = "ubuntu-kde_armhf_2022-06-07_01-06-rootfs.tar.zst"
old_sha256 = "e4b4c6969c8cfeb4e46063e5f775b01b8b8c5ca764aef9474a656b4730111c85"
# edition 2021
# DISTRO_NAME=ubuntu-dev_armhf
# ROOTFS_FILE=ubuntu-kde_armhf_2022-06-21_01-12-rootfs.tar.zst
# SHA256SUM=ad2cf4a16e2710f4dfe816d26ebc93c4f90e2644c336c3a14822b324e25e193c
# BUILD_DATE=20220621
# BUILD_TAG=2022-06-21
# STATUS=completed
# VERSION=latest01
# END_TIME=01:12

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-06-21
begin = 2022-06-21 00:18:09.916632782+00:00
start-sync_0 = 00:55:23
start-zstd = 00:58:29
start-sync_1 = 01:11:02
end-sync_1 = 01:12:13
end = 2022-06-21 01:12:13.424269171+00:00

[server]
repo = "cake233/ubuntu-kde-armv7"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = true
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (Ubuntu GLIBC 2.35-0ubuntu3) 2.35'
zsh = 'zsh 5.9 (arm-unknown-linux-gnueabihf)'

[port]
tcp = [5902, 36080]
