[main]
name = "dotnet"
tag = ["latest", "2023-06-05", ".NET", "dotnet-sdk"]
os = "arch"
release = "latest"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "dotnet_amd64_2023-06-05_12-17.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "77586e261765f280db1254fe9a592e45b51cd5a0a3375b63c48ddbb2885c2ac8"

# zstd: [1-22]
zstd-level = 22

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "1.8G"
tar_bytes = 1872870400

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "436M"
zstd_bytes = 456167983

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20230522"
previous_tag = "2023-05-22"
previous_file = "dotnet_amd64_2023-05-22_12-19-rootfs.tar.zst"
previous_sha256 = "97f52793fc25438ebaaef2f6bd4c0974c9c8f57477175a09c21fe6992d9eedd6"

current_version = "latest02"
current_date = "20230605"
old_file = "dotnet_amd64_2023-05-08_12-22-rootfs.tar.zst"
old_sha256 = "435c5e07bebabfd38b71ecb2eb331b04acc52ace878c3537c68b01191d12abce"
# edition 2021
# DISTRO_NAME=dotnet_amd64
# ROOTFS_FILE=dotnet_amd64_2023-06-05_12-17-rootfs.tar.zst
# SHA256SUM=77586e261765f280db1254fe9a592e45b51cd5a0a3375b63c48ddbb2885c2ac8
# BUILD_DATE=20230605
# BUILD_TAG=2023-06-05
# STATUS=completed
# VERSION=latest02
# END_TIME=12:17

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-06-05
begin = 2023-06-05 12:02:38.878139966+00:00
start-sync_0 = 12:06:25
start-zstd = 12:07:15
start-sync_1 = 12:16:59
end-sync_1 = 12:17:31
end = 2023-06-05 12:17:31.121975360+00:00

[server]
repo = "cake233/dotnet-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = true
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"
PATH = "/usr/local/powershell:/usr/local/dotnet/bin${PATH:+:${PATH}}"
DOTNET_ROOT = "/usr/local/dotnet"
DOTNET_RUNNING_IN_CONTAINER = true
ASPNETCORE_URLS = ""
DOTNET_GENERATE_ASPNET_CERTIFICATE = false
DOTNET_USE_POLLING_FILE_WATCHER = true
Logging__Console__FormatterName = ""
NUGET_XMLDOC_MODE = "skip"

[version]
ldd = 'ldd (GNU libc) 2.37'
git = 'git version 2.41.0'
dotnet = '7.0.302'
powershell = 'PowerShell 7.3.4'
dotnet_info = '''
.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/local/dotnet/sdk/7.0.302/

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.302 [/usr/local/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/local/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
'''

[other]
cmd = "/usr/local/powershell/pwsh"
