[main]
name = "dotnet"
tag = ["latest", "2023-07-31", ".NET", "dotnet-sdk"]
os = "arch"
release = "latest"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "dotnet_amd64_2023-07-31_12-19.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "9b6d334d196c091784300ed7232ad03b560677b620a2dce1ded1317344bde9b0"

# zstd: [1-22]
zstd-level = 22

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "1.8G"
tar_bytes = 1885466112

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "435M"
zstd_bytes = 455548030

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20230717"
previous_tag = "2023-07-17"
previous_file = "dotnet_amd64_2023-07-17_12-17-rootfs.tar.zst"
previous_sha256 = "624252ae7cfe0188d90ccff2138c4a156631b823f7648b9cc3f142fd945eb0b0"

current_version = "latest02"
current_date = "20230731"
old_file = "dotnet_amd64_2023-07-03_12-18-rootfs.tar.zst"
old_sha256 = "e59e795965179851b980abe6b03201ba557413883033b92355549fed9abeea27"
# edition 2021
# DISTRO_NAME=dotnet_amd64
# ROOTFS_FILE=dotnet_amd64_2023-07-31_12-19-rootfs.tar.zst
# SHA256SUM=9b6d334d196c091784300ed7232ad03b560677b620a2dce1ded1317344bde9b0
# BUILD_DATE=20230731
# BUILD_TAG=2023-07-31
# STATUS=completed
# VERSION=latest02
# END_TIME=12:19

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-07-31
begin = 2023-07-31 12:02:39.121229823+00:00
start-sync_0 = 12:06:58
start-zstd = 12:07:52
start-sync_1 = 12:19:07
end-sync_1 = 12:19:51
end = 2023-07-31 12:19:51.252595124+00:00

[server]
repo = "cake233/dotnet-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = true
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"
PATH = "/usr/local/powershell:/usr/local/dotnet/bin${PATH:+:${PATH}}"
DOTNET_ROOT = "/usr/local/dotnet"
DOTNET_RUNNING_IN_CONTAINER = true
ASPNETCORE_URLS = ""
DOTNET_GENERATE_ASPNET_CERTIFICATE = false
DOTNET_USE_POLLING_FILE_WATCHER = true
Logging__Console__FormatterName = ""
NUGET_XMLDOC_MODE = "skip"

[version]
ldd = 'ldd (GNU libc) 2.37'
git = 'git version 2.41.0'
dotnet = '7.0.306'
powershell = 'PowerShell 7.3.6'
dotnet_info = '''
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/local/dotnet/sdk/7.0.306/

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  7.0.306 [/usr/local/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.9 [/usr/local/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.9 [/usr/local/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/local/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
'''

[other]
cmd = "/usr/local/powershell/pwsh"
