[main]
name = "go"
tag = ["alpine", "2022-10-03", "musl-libc", "musl"]
os = "alpine"
release = "stable"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "go-musl_amd64_2022-10-03_12-07.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "46e9ed56537f8200aff67885310bfeccd914bd308cbdf510a109d7f8381051d7"

# zstd: [1-22]
zstd-level = 22

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "361M"
tar_bytes = 377784320

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "86M"
zstd_bytes = 89339057

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20220919"
previous_tag = "2022-09-19"
previous_file = "go-musl_amd64_2022-09-19_12-07-rootfs.tar.zst"
previous_sha256 = "9f9d07ff30efe3713fc2bec9c90d6a44e42283bb90d4796fb353edb79b86dbbc"

current_version = "latest02"
current_date = "20221003"
old_file = "go-musl_amd64_2022-09-05_12-07-rootfs.tar.zst"
old_sha256 = "b75ae5551ee4e1f23f6afa5ece79532b6a53f08ca70c02c55ec3e82f89bb0066"
# edition 2021
# DISTRO_NAME=go_amd64
# ROOTFS_FILE=go-musl_amd64_2022-10-03_12-07-rootfs.tar.zst
# SHA256SUM=46e9ed56537f8200aff67885310bfeccd914bd308cbdf510a109d7f8381051d7
# BUILD_DATE=20221003
# BUILD_TAG=2022-10-03
# STATUS=completed
# VERSION=latest02
# END_TIME=12:07

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-10-03
begin = 2022-10-03 12:02:27.086269765+00:00
start-sync_0 = 12:03:27
start-zstd = 12:03:40
start-sync_1 = 12:07:23
end-sync_1 = 12:07:37
end = 2022-10-03 12:07:37.068982825+00:00

[server]
repo = "cake233/go-alpine-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = true
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "C.UTF-8"
PATH = "/go/bin:/usr/local/go/bin${PATH:+:${PATH}}"
GOPATH = "/go"

[version]
ldd = 'musl libc (x86_64) Version 1.2.3'
go = 'go version go1.19.1 linux/amd64'
gofmt = '/usr/local/go/bin/gofmt: go1.19.1'

[other]
workdir = "/go"
