[main]
name = "rust"
tag = ["latest", "2022-06-17", "nightly", "unstable", "default", "gnu-libc"]
os = "debian"
release = "sid"
arch = "arm64"
platform = "linux/arm64"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "rust_arm64_2022-06-17_03-06.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "1133e2c13273e7c1469c998aa9d57283b5b09645d1b4e11ab658c5ba76629e25"

# zstd: [1-22]
zstd-level = 20

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "1.8G"
tar_bytes = 1827113472

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "258M"
zstd_bytes = 269535295

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20220613"
previous_tag = "2022-06-13"
previous_file = "rust_arm64_2022-06-13_03-06-rootfs.tar.zst"
previous_sha256 = "20bafcd6e3b4db8f81d0366afe378f89638e05736c96fbe8c3454c6a0f8ae48f"

current_version = "latest01"
current_date = "20220617"
old_file = "rust_arm64_2022-06-10_03-06-rootfs.tar.zst"
old_sha256 = "a377728b8b5e9450d369919204656ba89917537391a0b01f7ce48fbf44aec2ec"
# edition 2021
# DISTRO_NAME=rust_arm64
# ROOTFS_FILE=rust_arm64_2022-06-17_03-06-rootfs.tar.zst
# SHA256SUM=1133e2c13273e7c1469c998aa9d57283b5b09645d1b4e11ab658c5ba76629e25
# BUILD_DATE=20220617
# BUILD_TAG=2022-06-17
# STATUS=completed
# VERSION=latest01
# END_TIME=03:06

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-06-17
begin = 2022-06-17 02:52:35.103265933+00:00
start-sync_0 = 02:58:48
start-zstd = 02:59:53
start-sync_1 = 03:05:48
end-sync_1 = 03:06:07
end = 2022-06-17 03:06:07.419074625+00:00

[server]
repo = "cake233/rust-arm64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
start_sync = 2022-06-17 05:07:58.555759437+00:00
end_sync = 2022-06-17 05:09:14.231853563+00:00
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"
PATH = "/usr/local/cargo/bin${PATH:+:${PATH}}"
RUSTUP_HOME = "/usr/local/rustup"
CARGO_HOME = "/usr/local/cargo"

[version]
ldd = 'ldd (Debian GLIBC 2.33-7) 2.33'
rustup = 'rustup 1.24.3 (ce5817a94 2021-05-31)'
cargo = 'cargo 1.63.0-nightly (4d92f07f3 2022-06-09)'
rustc = 'rustc 1.63.0-nightly (cacc75c82 2022-06-16)'
cc = 'cc (Debian 11.3.0-3) 11.3.0'
cargo_verbose = '''
cargo 1.63.0-nightly (4d92f07f3 2022-06-09)
release: 1.63.0-nightly
commit-hash: 4d92f07f34ba7fb7d7f207564942508f46c225d3
commit-date: 2022-06-09
host: aarch64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1n)
os: Linux [64-bit]
'''
rustc_verbose = '''
rustc 1.63.0-nightly (cacc75c82 2022-06-16)
binary: rustc
commit-hash: cacc75c82ebe15cf63d31034fcf7f1016cddf0e2
commit-date: 2022-06-16
host: aarch64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.5
'''
