[main]
name = "rust"
tag = ["latest", "2023-09-04", "nightly", "unstable", "default", "gnu-libc"]
os = "debian"
release = "sid"
arch = "s390x"
platform = "linux/s390x"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "rust_s390x_2023-09-04_03-07.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "9062e6dd99f1b563f5fb3adfa71f7668a2d1f15036366f01f95356889d206f08"

# zstd: [1-22]
zstd-level = 20

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "1.9G"
tar_bytes = 1935725056

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "244M"
zstd_bytes = 255095710

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20211128"
previous_tag = ""
previous_file = ""
previous_sha256 = ""

current_version = "latest01"
current_date = "20230904"
old_file = ""
old_sha256 = ""
# edition 2021
# DISTRO_NAME=rust_s390x
# ROOTFS_FILE=rust_s390x_2023-09-04_03-07-rootfs.tar.zst
# SHA256SUM=9062e6dd99f1b563f5fb3adfa71f7668a2d1f15036366f01f95356889d206f08
# BUILD_DATE=20230904
# BUILD_TAG=2023-09-04
# STATUS=completed
# VERSION=latest01
# END_TIME=03:07

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-09-04
begin = 2023-09-04 02:52:33.737258489+00:00
start-sync_0 = 02:59:45
start-zstd = 03:00:52
start-sync_1 = 03:07:16
end-sync_1 = 03:07:37
end = 2023-09-04 03:07:37.129557377+00:00

[server]
repo = "cake233/rust-s390x"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = true
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"
PATH = "/usr/local/cargo/bin${PATH:+:${PATH}}"
RUSTUP_HOME = "/usr/local/rustup"
CARGO_HOME = "/usr/local/cargo"

[version]
ldd = 'ldd (Debian GLIBC 2.37-7) 2.37'
rustup = 'rustup 1.26.0 (5af9b9484 2023-04-05)'
cargo = 'cargo 1.74.0-nightly (96fe1c9e1 2023-08-29)'
rustc = 'rustc 1.74.0-nightly (58e967a9c 2023-09-03)'
cc = 'cc (Debian 13.2.0-3) 13.2.0'
cargo_verbose = '''
cargo 1.74.0-nightly (96fe1c9e1 2023-08-29)
release: 1.74.0-nightly
commit-hash: 96fe1c9e1aecd8f57063e3753969bb6418fd2fd5
commit-date: 2023-08-29
host: s390x-unknown-linux-gnu
libgit2: 1.7.1 (sys:0.18.0 vendored)
libcurl: 8.2.1-DEV (sys:0.4.65+curl-8.2.1 vendored ssl:OpenSSL/1.1.1u)
ssl: OpenSSL 1.1.1u  30 May 2023
os: Linux [64-bit]
'''
rustc_verbose = '''
rustc 1.74.0-nightly (58e967a9c 2023-09-03)
binary: rustc
commit-hash: 58e967a9cc3bd39122e8cb728e8cec6e3a4eeef2
commit-date: 2023-09-03
host: s390x-unknown-linux-gnu
release: 1.74.0-nightly
LLVM version: 17.0.0
'''
