[main]
name = "rust"
tag = ["latest", "2022-06-24", "nightly", "unstable", "default", "gnu-libc"]
os = "debian"
release = "sid"
arch = "armhf"
platform = "linux/arm/v7"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "rust_armhf_2022-06-24_03-05.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "1e124f13ac8165d272abb7c37fc792efe848f45bca469df6c3d465a0910e34b6"

# zstd: [1-22]
zstd-level = 20

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "1.5G"
tar_bytes = 1558175232

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "235M"
zstd_bytes = 245614924

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20220620"
previous_tag = "2022-06-20"
previous_file = "rust_armhf_2022-06-20_03-06-rootfs.tar.zst"
previous_sha256 = "c1ccaab1723fbd9bcab6ddc0e3db831b2d15758c0bc96baaea0991021de273dc"

current_version = "latest02"
current_date = "20220624"
old_file = "rust_armhf_2022-06-17_03-05-rootfs.tar.zst"
old_sha256 = "962f586c7247dfda14bdd3db0a6fef7216e1020c459831e6a006d7159b92870f"
# edition 2021
# DISTRO_NAME=rust_armhf
# ROOTFS_FILE=rust_armhf_2022-06-24_03-05-rootfs.tar.zst
# SHA256SUM=1e124f13ac8165d272abb7c37fc792efe848f45bca469df6c3d465a0910e34b6
# BUILD_DATE=20220624
# BUILD_TAG=2022-06-24
# STATUS=completed
# VERSION=latest02
# END_TIME=03:05

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-06-24
begin = 2022-06-24 02:52:28.332866117+00:00
start-sync_0 = 02:59:15
start-zstd = 03:00:18
start-sync_1 = 03:05:29
end-sync_1 = 03:05:51
end = 2022-06-24 03:05:51.344615168+00:00

[server]
repo = "cake233/rust-armv7"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = true
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"
PATH = "/usr/local/cargo/bin${PATH:+:${PATH}}"
RUSTUP_HOME = "/usr/local/rustup"
CARGO_HOME = "/usr/local/cargo"

[version]
ldd = 'ldd (Debian GLIBC 2.33-7) 2.33'
rustup = 'rustup 1.24.3 (ce5817a94 2021-05-31)'
cargo = 'cargo 1.63.0-nightly (03a849043 2022-06-19)'
rustc = 'rustc 1.63.0-nightly (43347397f 2022-06-23)'
cc = 'cc (Debian 11.3.0-3) 11.3.0'
cargo_verbose = '''
cargo 1.63.0-nightly (03a849043 2022-06-19)
release: 1.63.0-nightly
commit-hash: 03a849043e25104e8b7ad0d4a96c525787b69379
commit-date: 2022-06-19
host: armv7-unknown-linux-gnueabihf
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1n)
os: Linux [32-bit]
'''
rustc_verbose = '''
rustc 1.63.0-nightly (43347397f 2022-06-23)
binary: rustc
commit-hash: 43347397f7c5ca9a670a3bb3890c7187e24a52ab
commit-date: 2022-06-23
host: armv7-unknown-linux-gnueabihf
release: 1.63.0-nightly
LLVM version: 14.0.5
'''
