[main]
name = "fedora"
tag = ["zsh", "2022-02-01"]
os = "fedora"
release = "rawhide"
arch = "amd64"
platform = "linux/amd64"
x11_or_wayland = false

[file]
name = "fedora-zsh_amd64_2022-02-01_12-10.tar.zst"

version = "0.0.0-alpha.2"

# This value can be used to verify the integrity of the file
sha256 = "58ca79c46755f82cfb167422846a1845786e47426ce5e998309756a0da46c028"

# zstd: [1-22]
zstd-level = 20

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "963M"
tar_bytes = 1009092608

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "165M"
zstd_bytes = 172397612

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20220125"
previous_tag = "2022-01-25"
previous_file = "fedora-zsh_amd64_2022-01-25_12-10-rootfs.tar.zst"
previous_sha256 = "83fd49cf1ade258b442b93ab23a698a2a667056650bb3f3d52145a5d43065e65"

current_version = "latest01"
current_date = "20220201"
old_file = "fedora-zsh_amd64_2022-01-18_12-09-rootfs.tar.zst"
old_sha256 = "9ecd6f6cc302d020726b50bb9501b6ff7aa9927c9b636b59b9faeb83ff64030b"
# edition 2021
# DISTRO_NAME=fedora-rawhide_amd64
# ROOTFS_FILE=fedora-zsh_amd64_2022-02-01_12-10-rootfs.tar.zst
# SHA256SUM=58ca79c46755f82cfb167422846a1845786e47426ce5e998309756a0da46c028
# BUILD_DATE=20220201
# BUILD_TAG=2022-02-01
# STATUS=completed
# VERSION=latest01
# END_TIME=12:10

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-02-01
begin = 2022-02-01 12:02:24.396126707+00:00
start-sync_0 = 12:04:23
start-zstd = 12:06:26
start-sync_1 = 12:10:02
end-sync_1 = 12:10:19
end = 2022-02-01 12:10:19.117197979+00:00

[server]
repo = "cake233/fedora-zsh-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
start_sync = 2022-02-01 18:02:50.849138472+00:00
end_sync = 2022-02-01 18:03:36.371552013+00:00
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (GNU libc) 2.34.9000'
zsh = 'zsh 5.8 (x86_64-redhat-linux-gnu)'
