[main]
name = "fedora"
tag = ["lxqt", "2022-02-15"]
os = "fedora"
release = "rawhide"
arch = "arm64"
platform = "linux/arm64"
x11_or_wayland = true

[file]
name = "fedora-lxqt_arm64_2022-02-15_13-57.tar.zst"

version = "0.0.0-alpha.2"

# This value can be used to verify the integrity of the file
sha256 = "d18289fa8e1bbb9befb528f7d0f34e970c753332d7fee2e8c7a9a392e3a452a3"

# zstd: [1-22]
zstd-level = 18

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "4.2G"
tar_bytes = 4497694720

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "971M"
zstd_bytes = 1017361429

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20211102"
previous_tag = ""
previous_file = "fedora-rawhide_arm64+lxqt-2021_11-02-rootfs.tar.zst"
previous_sha256 = "3148521c15bba60de747c6f5fbfdbf3f1591601ec23bd53a319bd3d8a3cd444e"

current_version = "latest02"
current_date = "20220215"
old_file = "fedora-rawhide_arm64+lxqt-2021_10-26-rootfs.tar.zst"
old_sha256 = "3e47a4fc80dd5ee4013b9db146ae5c2c5713ea0884d27d3d45508ac9c3127ab3"
# edition 2021
# DISTRO_NAME=fedora-rawhide_arm64
# ROOTFS_FILE=fedora-lxqt_arm64_2022-02-15_13-57-rootfs.tar.zst
# SHA256SUM=d18289fa8e1bbb9befb528f7d0f34e970c753332d7fee2e8c7a9a392e3a452a3
# BUILD_DATE=20220215
# BUILD_TAG=2022-02-15
# STATUS=completed
# VERSION=latest02
# END_TIME=13:57

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-02-15
begin = 2022-02-15 13:02:49.032756465+00:00
start-sync_0 = 13:41:22
start-zstd = 13:44:50
start-sync_1 = 13:56:52
end-sync_1 = 13:57:54
end = 2022-02-15 13:57:54.683275083+00:00

[server]
repo = "cake233/fedora-lxqt-arm64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = false
previous = true
in_sync = false
split = false

[server.node3]
name = "azure"
current = false
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (GNU libc) 2.35'
zsh = 'zsh 5.8.1 (aarch64-redhat-linux-gnu)'

[port]
tcp = [5902, 36080]
