[main]
name = "fedora"
tag = ["lxqt", "2022-06-21"]
os = "fedora"
release = "rawhide"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "fedora-lxqt_amd64_2022-06-21_13-23.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "70e2118d721a2b4d4aa7a6b3cfc7130b78f9520942b6d2bc5b40d8e8e97985af"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "3.3G"
tar_bytes = 3498974208

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "909M"
zstd_bytes = 952214711

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20211102"
previous_tag = ""
previous_file = "fedora-rawhide_amd64+lxqt-2021_11-02-rootfs.tar.zst"
previous_sha256 = "fc546284d21dbef914c7cafb3d7006b02cae4a8633067745fd826e8f3597cb70"

current_version = "latest02"
current_date = "20220621"
old_file = "fedora-rawhide_amd64+lxqt-2021_10-26-rootfs.tar.zst"
old_sha256 = "e507e03c2fba7bde2a8166834367ba9a4d407b87840550d3504aab03a9f877c1"
# edition 2021
# DISTRO_NAME=fedora-rawhide_amd64
# ROOTFS_FILE=fedora-lxqt_amd64_2022-06-21_13-23-rootfs.tar.zst
# SHA256SUM=70e2118d721a2b4d4aa7a6b3cfc7130b78f9520942b6d2bc5b40d8e8e97985af
# BUILD_DATE=20220621
# BUILD_TAG=2022-06-21
# STATUS=completed
# VERSION=latest02
# END_TIME=13:23

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-06-21
begin = 2022-06-21 13:02:39.781353330+00:00
start-sync_0 = 13:06:30
start-zstd = 13:08:54
start-sync_1 = 13:22:19
end-sync_1 = 13:23:22
end = 2022-06-21 13:23:22.821279941+00:00

[server]
repo = "cake233/fedora-lxqt-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = true
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (GNU libc) 2.35.9000'
zsh = 'zsh 5.9 (x86_64-redhat-linux-gnu)'

[port]
tcp = [5902, 36080]
