[main]
name = "node"
tag = ["latest", "2022-12-19"]
os = "debian"
release = "stable"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "node_amd64_2022-12-19_12-15.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "8b7303c4bf94cea973b65b574fb37fbc165bef3d1e37ab1a71ae3a1dee6862ab"

# zstd: [1-22]
zstd-level = 22

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "999M"
tar_bytes = 1046685184

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "199M"
zstd_bytes = 208435355

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20221205"
previous_tag = "2022-12-05"
previous_file = "node_amd64_2022-12-05_12-13-rootfs.tar.zst"
previous_sha256 = "47d780310385425ba7ce82c537104809079454e0f9c205b10d12f27048c54ebd"

current_version = "latest02"
current_date = "20221219"
old_file = "node_amd64_2022-11-21_12-15-rootfs.tar.zst"
old_sha256 = "f37a54f4c49a8d5c573e9e91dc57acb2e8fce7603680cbe45d71d0e1042d512b"
# edition 2021
# DISTRO_NAME=node_amd64
# ROOTFS_FILE=node_amd64_2022-12-19_12-15-rootfs.tar.zst
# SHA256SUM=8b7303c4bf94cea973b65b574fb37fbc165bef3d1e37ab1a71ae3a1dee6862ab
# BUILD_DATE=20221219
# BUILD_TAG=2022-12-19
# STATUS=completed
# VERSION=latest02
# END_TIME=12:15

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-12-19
begin = 2022-12-19 12:02:34.554490655+00:00
start-sync_0 = 12:04:39
start-zstd = 12:06:19
start-sync_1 = 12:15:25
end-sync_1 = 12:15:45
end = 2022-12-19 12:15:45.609729213+00:00

[server]
repo = "cake233/node-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = true
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (Debian GLIBC 2.31-13+deb11u5) 2.31'
node = 'v19.3.0'
yarn = '1.22.19'
npm = '9.2.0'
