[main]
name = "node"
tag = ["alpine", "2023-02-27", "musl-libc", "musl"]
os = "alpine"
release = "stable"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "node-musl_amd64_2023-02-27_12-05.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "5e9c1d8b3d020245d0a784ee8ae4a070edf9bdcd1fccba8c99c6ad0af0e913e7"

# zstd: [1-22]
zstd-level = 22

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "189M"
tar_bytes = 197726720

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "35M"
zstd_bytes = 35674310

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20230213"
previous_tag = "2023-02-13"
previous_file = "node-musl_amd64_2023-02-13_12-04-rootfs.tar.zst"
previous_sha256 = "4369102490c06f5a95d20aa236350ef9fe5346ad7d05e894e50dc16c1c246b6b"

current_version = "latest01"
current_date = "20230227"
old_file = "node-musl_amd64_2023-01-30_12-04-rootfs.tar.zst"
old_sha256 = "58bd3729d1cafcebea93ac5bd6966baa500f5899cf718e78fbb696e83b508c12"
# edition 2021
# DISTRO_NAME=node_amd64
# ROOTFS_FILE=node-musl_amd64_2023-02-27_12-05-rootfs.tar.zst
# SHA256SUM=5e9c1d8b3d020245d0a784ee8ae4a070edf9bdcd1fccba8c99c6ad0af0e913e7
# BUILD_DATE=20230227
# BUILD_TAG=2023-02-27
# STATUS=completed
# VERSION=latest01
# END_TIME=12:05

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-02-27
begin = 2023-02-27 12:02:41.529893736+00:00
start-sync_0 = 12:03:31
start-zstd = 12:03:44
start-sync_1 = 12:05:04
end-sync_1 = 12:05:15
end = 2023-02-27 12:05:15.874447906+00:00

[server]
repo = "cake233/node-alpine-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = true
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "C.UTF-8"

[version]
ldd = 'musl libc (x86_64) Version 1.2.3'
node = 'v19.7.0'
yarn = '1.22.19'
npm = '9.5.0'
