[main]
name = "debian"
tag = ["mate", "2022-04-13"]
os = "debian"
release = "sid"
arch = "amd64"
platform = "linux/amd64"
x11_or_wayland = true
syntax_version = "0.0.0-alpha.3"

[file]
name = "debian-mate_amd64_2022-04-13_12-49.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "297a7c1493ae77b09fc2b340a5ff5d2495bd636057c5f50b5f8babebfa6f7acf"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "4.0G"
tar_bytes = 4216309248

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "1.1G"
zstd_bytes = 1146779717

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20220406"
previous_tag = "2022-04-06"
previous_file = "debian-mate_amd64_2022-04-06_11-56-rootfs.tar.zst"
previous_sha256 = "82e5917674531fa483ab73c41683f415a0c18fe320c85de0dadf90eaa018f38f"

current_version = "latest01"
current_date = "20220413"
old_file = "debian-mate_amd64_2022-03-30_11-43-rootfs.tar.zst"
old_sha256 = "70ee79f86297d140ed85dc2bbb7fcd575168cfd48072df6d3c45bce8682422b3"
# edition 2021
# DISTRO_NAME=debian-sid_amd64
# ROOTFS_FILE=debian-mate_amd64_2022-04-13_12-49-rootfs.tar.zst
# SHA256SUM=297a7c1493ae77b09fc2b340a5ff5d2495bd636057c5f50b5f8babebfa6f7acf
# BUILD_DATE=20220413
# BUILD_TAG=2022-04-13
# STATUS=completed
# VERSION=latest01
# END_TIME=12:49

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-04-13
begin = 2022-04-13 12:21:41.609560717+00:00
start-sync_0 = 12:28:05
start-zstd = 12:32:18
start-sync_1 = 12:48:16
end-sync_1 = 12:49:34
end = 2022-04-13 12:49:34.278474733+00:00

[server]
repo = "cake233/debian-mate-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
start_sync = 2022-04-13 18:24:31.005633441+00:00
end_sync = 2022-04-13 18:29:59.762160025+00:00
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (Debian GLIBC 2.33-7) 2.33'
zsh = 'zsh 5.8.1 (x86_64-debian-linux-gnu)'

[port]
tcp = [5902, 36080]
