[main]
name = "debian"
tag = ["zsh", "2022-06-15"]
os = "debian"
release = "sid"
arch = "i386"
platform = "linux/386"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "debian-zsh_i386_2022-06-15_12-18.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "cb5b99b76ccb361110badfde99ce0c2ef0c2ad3f75515c88388b3aba479685c1"

# zstd: [1-22]
zstd-level = 20

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "756M"
tar_bytes = 791734272

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "150M"
zstd_bytes = 156576329

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20220608"
previous_tag = "2022-06-08"
previous_file = "debian-zsh_i386_2022-06-08_12-19-rootfs.tar.zst"
previous_sha256 = "2ad638394dd9f847f03db7368ca764344db906a085f117afcae78820284b168a"

current_version = "latest02"
current_date = "20220615"
old_file = "debian-zsh_i386_2022-06-01_12-19-rootfs.tar.zst"
old_sha256 = "bd15799f2ae81231a56d870daac1ef8e9c720fd521cc7fe73510abcb44f9c633"
# edition 2021
# DISTRO_NAME=debian-sid_i386
# ROOTFS_FILE=debian-zsh_i386_2022-06-15_12-18-rootfs.tar.zst
# SHA256SUM=cb5b99b76ccb361110badfde99ce0c2ef0c2ad3f75515c88388b3aba479685c1
# BUILD_DATE=20220615
# BUILD_TAG=2022-06-15
# STATUS=completed
# VERSION=latest02
# END_TIME=12:18

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-06-15
begin = 2022-06-15 12:02:40.798535086+00:00
start-sync_0 = 12:14:30
start-zstd = 12:16:14
start-sync_1 = 12:18:43
end-sync_1 = 12:18:57
end = 2022-06-15 12:18:57.615065287+00:00

[server]
repo = "cake233/debian-zsh-386"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (Debian GLIBC 2.33-7) 2.33'
zsh = 'zsh 5.9 (i686-debian-linux-gnu)'
