[main]
name = "debian"
tag = ["kde", "2023-01-25"]
os = "debian"
release = "sid"
arch = "arm64"
platform = "linux/arm64"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "debian-kde_arm64_2023-01-25_13-45.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "85574555f1ec3917d9aa9a59149e64c6e12906fdb713314b99ae32b97c7b3a7d"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "6.1G"
tar_bytes = 6498598912

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "1.7G"
zstd_bytes = 1793725044

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20230118"
previous_tag = "2023-01-18"
previous_file = "debian-kde_arm64_2023-01-18_13-36-rootfs.tar.zst"
previous_sha256 = "9b550513eeef234707028436f175bbeb35b72e274feebd9a5cf83f8f8d3fc39b"

current_version = "latest01"
current_date = "20230125"
old_file = "debian-kde_arm64_2023-01-11_13-29-rootfs.tar.zst"
old_sha256 = "8d6e7497b09ebc5451bf623729a964c159c8ab8daf6533254ef3cad2361c3b2e"
# edition 2021
# DISTRO_NAME=debian-sid_arm64
# ROOTFS_FILE=debian-kde_arm64_2023-01-25_13-45-rootfs.tar.zst
# SHA256SUM=85574555f1ec3917d9aa9a59149e64c6e12906fdb713314b99ae32b97c7b3a7d
# BUILD_DATE=20230125
# BUILD_TAG=2023-01-25
# STATUS=completed
# VERSION=latest01
# END_TIME=13:45

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-01-25
begin = 2023-01-25 12:21:41.673495501+00:00
start-sync_0 = 13:11:55
start-zstd = 13:18:56
start-sync_1 = 13:43:24
end-sync_1 = 13:45:27
end = 2023-01-25 13:45:27.447130203+00:00

[server]
repo = "cake233/debian-kde-arm64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = true
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (Debian GLIBC 2.36-8) 2.36'
zsh = 'zsh 5.9 (aarch64-unknown-linux-gnu)'

[port]
tcp = [5902, 36080]
