[main]
name = "debian"
tag = ["mate", "2022-12-14"]
os = "debian"
release = "sid"
arch = "arm64"
platform = "linux/arm64"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "debian-mate_arm64_2022-12-14_13-12.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "b3fecc3b9e114e9aa6bc46b52f703a9b9aaf73504f2f28fdb7a88c12840b8c55"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "4.2G"
tar_bytes = 4460605440

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "1.2G"
zstd_bytes = 1193054779

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20221207"
previous_tag = "2022-12-07"
previous_file = "debian-mate_arm64_2022-12-07_13-16-rootfs.tar.zst"
previous_sha256 = "5840e23b4bc896b376142426e65a142a9559b791543e09a9572ddd078fa135e0"

current_version = "latest01"
current_date = "20221214"
old_file = "debian-mate_arm64_2022-11-30_13-12-rootfs.tar.zst"
old_sha256 = "0ac932656944acbd3f800025867d9b0c5b389ff9895854072c89f04350091df0"
# edition 2021
# DISTRO_NAME=debian-sid_arm64
# ROOTFS_FILE=debian-mate_arm64_2022-12-14_13-12-rootfs.tar.zst
# SHA256SUM=b3fecc3b9e114e9aa6bc46b52f703a9b9aaf73504f2f28fdb7a88c12840b8c55
# BUILD_DATE=20221214
# BUILD_TAG=2022-12-14
# STATUS=completed
# VERSION=latest01
# END_TIME=13:12

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-12-14
begin = 2022-12-14 12:21:12.847034948+00:00
start-sync_0 = 12:53:20
start-zstd = 12:56:54
start-sync_1 = 13:11:10
end-sync_1 = 13:12:15
end = 2022-12-14 13:12:15.487252648+00:00

[server]
repo = "cake233/debian-mate-arm64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
start_sync = 2022-12-14 18:21:46.550438432+00:00
end_sync = 2022-12-14 18:24:36.836470310+00:00
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (Debian GLIBC 2.36-6) 2.36'
zsh = 'zsh 5.9 (aarch64-unknown-linux-gnu)'

[port]
tcp = [5902, 36080]
