[main]
name = "debian"
tag = ["lxde", "2022-05-11"]
os = "debian"
release = "sid"
arch = "i386"
platform = "linux/386"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "debian-lxde_i386_2022-05-11_13-08.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "276fe2a879dec1c92829741c10592778a7825d249b71fa237a4d04e1e365284c"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "3.9G"
tar_bytes = 4137005568

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "1.1G"
zstd_bytes = 1178442638

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20220504"
previous_tag = "2022-05-04"
previous_file = "debian-lxde_i386_2022-05-04_15-28-rootfs.tar.zst"
previous_sha256 = "5b879d14a58da0d5cacef6eb6c49d9194b3afc775790f429518028d4a90e07a6"

current_version = "latest01"
current_date = "20220511"
old_file = "debian-lxde_i386_2022-04-27_13-12-rootfs.tar.zst"
old_sha256 = "2b6a96c8ee871b232f3dd08e8386b2ab3b2bd87fb9272abd54f8d392d54b6ec8"
# edition 2021
# DISTRO_NAME=debian-sid_i386
# ROOTFS_FILE=debian-lxde_i386_2022-05-11_13-08-rootfs.tar.zst
# SHA256SUM=276fe2a879dec1c92829741c10592778a7825d249b71fa237a4d04e1e365284c
# BUILD_DATE=20220511
# BUILD_TAG=2022-05-11
# STATUS=completed
# VERSION=latest01
# END_TIME=13:08

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-05-11
begin = 2022-05-11 12:19:20.455060719+00:00
start-sync_0 = 12:50:29
start-zstd = 12:53:55
start-sync_1 = 13:07:38
end-sync_1 = 13:08:50
end = 2022-05-11 13:08:50.458054502+00:00

[server]
repo = "cake233/debian-lxde-386"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
start_sync = 2022-05-11 18:10:01.600529232+00:00
end_sync = 2022-05-11 18:14:22.538916800+00:00
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (Debian GLIBC 2.33-7) 2.33'
zsh = 'zsh 5.8.1 (i686-debian-linux-gnu)'

[port]
tcp = [5902, 36080]
