[main]
name = "debian"
tag = ["kde", "2023-08-09"]
os = "debian"
release = "sid"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "debian-kde_amd64_2023-08-09_13-10.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "93705b00ed9687b0361d03c354f4bd019285c786fff52b90940a8e9f314e786b"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "6.0G"
tar_bytes = 6335290368

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "1.8G"
zstd_bytes = 1855977026

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20230802"
previous_tag = "2023-08-02"
previous_file = "debian-kde_amd64_2023-08-02_13-07-rootfs.tar.zst"
previous_sha256 = "083df37d2df7c7274c26bb7c814d8dc9458e5b1ba8bc173aa9f810fbd575c04b"

current_version = "latest01"
current_date = "20230809"
old_file = "debian-kde_amd64_2023-07-26_13-07-rootfs.tar.zst"
old_sha256 = "aeb3213d68809c092b571d8d5d67bd79957bf817e2cd3f9402b26db33d61a6aa"
# edition 2021
# DISTRO_NAME=debian-sid_amd64
# ROOTFS_FILE=debian-kde_amd64_2023-08-09_13-10-rootfs.tar.zst
# SHA256SUM=93705b00ed9687b0361d03c354f4bd019285c786fff52b90940a8e9f314e786b
# BUILD_DATE=20230809
# BUILD_TAG=2023-08-09
# STATUS=completed
# VERSION=latest01
# END_TIME=13:10

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-08-09
begin = 2023-08-09 12:22:50.147868465+00:00
start-sync_0 = 12:31:20
start-zstd = 12:38:51
start-sync_1 = 13:08:22
end-sync_1 = 13:10:50
end = 2023-08-09 13:10:50.522897086+00:00

[server]
repo = "cake233/debian-kde-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = true
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (Debian GLIBC 2.37-7) 2.37'
zsh = 'zsh 5.9 (x86_64-debian-linux-gnu)'

[port]
tcp = [5902, 36080]
