[main]
name = "php"
tag = ["latest", "2022-09-26"]
os = "debian"
release = "stable"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "php_amd64_2022-09-26_12-09.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "1fe52a224cddc910c51876a6de73dc9ca56edbcefd91fdd0899e558d9098c02f"

# zstd: [1-22]
zstd-level = 22

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "491M"
tar_bytes = 514127360

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "97M"
zstd_bytes = 101339423

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20220912"
previous_tag = "2022-09-12"
previous_file = "php_amd64_2022-09-12_12-09-rootfs.tar.zst"
previous_sha256 = "ded671cad0c4fd4390454fa76aec7b1a21b4eb32b7f3d1349dada648dacea77b"

current_version = "latest02"
current_date = "20220926"
old_file = "php_amd64_2022-08-29_12-10-rootfs.tar.zst"
old_sha256 = "361c3fea50ca9675d66b4a3d8508c8beb7b8908ec66ab9936845557ff8e9cc58"
# edition 2021
# DISTRO_NAME=php_amd64
# ROOTFS_FILE=php_amd64_2022-09-26_12-09-rootfs.tar.zst
# SHA256SUM=1fe52a224cddc910c51876a6de73dc9ca56edbcefd91fdd0899e558d9098c02f
# BUILD_DATE=20220926
# BUILD_TAG=2022-09-26
# STATUS=completed
# VERSION=latest02
# END_TIME=12:09

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-09-26
begin = 2022-09-26 12:02:37.345041893+00:00
start-sync_0 = 12:04:17
start-zstd = 12:04:31
start-sync_1 = 12:09:14
end-sync_1 = 12:09:26
end = 2022-09-26 12:09:26.907271322+00:00

[server]
repo = "cake233/php-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"
PHP_INI_DIR = '/usr/local/etc/php'

[version]
ldd = 'ldd (Debian GLIBC 2.31-13+deb11u4) 2.31'
php = '''
PHP 8.1.10 (cli) (built: Sep 13 2022 10:14:32) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies
'''

[other]
phpize_deps = 'autoconf 		dpkg-dev 		file 		g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c'
php_extra_configure_args = '--enable-embed'
php_cflags = '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
php_cppflags = '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
php_ldflags = '-Wl,-O1 -pie'
gpg_keys = '528995BFEDFBA7191D46839EF9BA0ADA31CBD89E 39B641343D8C104B2B146DC3F9C39DC0B9698544 F1F692238FBC1666E5A5CCD4199F9DFEF6FFBAFD'
php_url = 'https://www.php.net/distributions/php-8.1.10.tar.xz'
php_src_url = 'https://www.php.net/distributions/php-8.1.10.tar.xz.asc'
