[main]
name = "php"
tag = ["alpine", "2022-12-19", "musl-libc", "musl"]
os = "alpine"
release = "stable"
arch = "arm64"
platform = "linux/arm64"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "php-musl_arm64_2022-12-19_12-05.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "51336d4dce5cd1181c0f3341c101a98f35a993214307d82196d5228b36314a80"

# zstd: [1-22]
zstd-level = 22

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "104M"
tar_bytes = 108085760

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "26M"
zstd_bytes = 26368654

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20221205"
previous_tag = "2022-12-05"
previous_file = "php-musl_arm64_2022-12-05_12-04-rootfs.tar.zst"
previous_sha256 = "ba168b7cc35889216975ec25aa8dc3b8fbd0253cd2d6341fa0d7a55223836aba"

current_version = "latest02"
current_date = "20221219"
old_file = ""
old_sha256 = ""
# edition 2021
# DISTRO_NAME=php_arm64
# ROOTFS_FILE=php-musl_arm64_2022-12-19_12-05-rootfs.tar.zst
# SHA256SUM=51336d4dce5cd1181c0f3341c101a98f35a993214307d82196d5228b36314a80
# BUILD_DATE=20221219
# BUILD_TAG=2022-12-19
# STATUS=completed
# VERSION=latest02
# END_TIME=12:05

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-12-19
begin = 2022-12-19 12:02:31.783676101+00:00
start-sync_0 = 12:04:09
start-zstd = 12:04:14
start-sync_1 = 12:04:54
end-sync_1 = 12:05:00
end = 2022-12-19 12:05:00.638860467+00:00

[server]
repo = "cake233/php-alpine-arm64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = true
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "C.UTF-8"
PHP_INI_DIR = '/usr/local/etc/php'

[version]
ldd = 'musl libc (aarch64) Version 1.2.3'
php = '''
PHP 8.2.0 (cli) (built: Dec  8 2022 19:17:28) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.0, Copyright (c) Zend Technologies
'''

[other]
phpize_deps = 'autoconf 		dpkg-dev dpkg 		file 		g++ 		gcc 		libc-dev 		make 		pkgconf 		re2c'
php_extra_configure_args = '--enable-embed'
php_cflags = '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
php_cppflags = '-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
php_ldflags = '-Wl,-O1 -pie'
gpg_keys = '39B641343D8C104B2B146DC3F9C39DC0B9698544 E60913E4DF209907D8E30D96659A97C9CF2A795A 1198C0117593497A5EC5C199286AF1F9897469DC'
php_url = 'https://www.php.net/distributions/php-8.2.0.tar.xz'
php_src_url = 'https://www.php.net/distributions/php-8.2.0.tar.xz.asc'
