[main]
name = "arch"
tag = ["mate", "2023-03-08"]
os = "arch"
release = "latest"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "arch-mate_amd64_2023-03-08_00-57.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "fcf3a63c4e7e84cb2a24797f70bc7a2eb88f4332b91ca14afa16352e6bd0e2d9"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "4.5G"
tar_bytes = 4744560640

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "1.3G"
zstd_bytes = 1352822606

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20230301"
previous_tag = "2023-03-01"
previous_file = "arch-mate_amd64_2023-03-01_01-08-rootfs.tar.zst"
previous_sha256 = "c07bc23456d6ea49c9e851ccc70e877031960696649e3e0ac62a3ba355c8803b"

current_version = "latest01"
current_date = "20230308"
old_file = "arch-mate_amd64_2023-02-22_01-04-rootfs.tar.zst"
old_sha256 = "08b33ab65d1c93b2fb513652606240bc4266a3a068d01c6fc18d1b5cec34d61e"
# edition 2021
# DISTRO_NAME=arch_amd64
# ROOTFS_FILE=arch-mate_amd64_2023-03-08_00-57-rootfs.tar.zst
# SHA256SUM=fcf3a63c4e7e84cb2a24797f70bc7a2eb88f4332b91ca14afa16352e6bd0e2d9
# BUILD_DATE=20230308
# BUILD_TAG=2023-03-08
# STATUS=completed
# VERSION=latest01
# END_TIME=00:57

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-03-08
begin = 2023-03-08 00:30:35.271824145+00:00
start-sync_0 = 00:35:18
start-zstd = 00:40:01
start-sync_1 = 00:56:34
end-sync_1 = 00:57:51
end = 2023-03-08 00:57:51.869029221+00:00

[server]
repo = "cake233/arch-mate-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = true
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (GNU libc) 2.37'
zsh = 'zsh 5.9 (x86_64-pc-linux-gnu)'

[port]
tcp = [5902, 36080]
