[main]
name = "arch"
tag = ["zsh", "2023-01-18"]
os = "arch"
release = "latest"
arch = "armhf"
platform = "linux/arm/v7"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "arch-zsh_armhf_2023-01-18_00-27.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "5c5a06851282725102dd18b67245a20ec7641ed99cd16bb16e48bd270e984e03"

# zstd: [1-22]
zstd-level = 20

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "904M"
tar_bytes = 947052032

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "221M"
zstd_bytes = 231308964

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20230111"
previous_tag = "2023-01-11"
previous_file = "arch-zsh_armhf_2023-01-11_00-26-rootfs.tar.zst"
previous_sha256 = "392d9be0492aa2ff39bd68e757c5b838b599653af8df429c541c38efc767b63e"

current_version = "latest02"
current_date = "20230118"
old_file = "arch-zsh_armhf_2023-01-04_00-31-rootfs.tar.zst"
old_sha256 = "abd37bc5f41cc53c25680d08f587a9f1a95e9e5b1b7e9fe3ac89c0bf691f7402"
# edition 2021
# DISTRO_NAME=arch_armhf
# ROOTFS_FILE=arch-zsh_armhf_2023-01-18_00-27-rootfs.tar.zst
# SHA256SUM=5c5a06851282725102dd18b67245a20ec7641ed99cd16bb16e48bd270e984e03
# BUILD_DATE=20230118
# BUILD_TAG=2023-01-18
# STATUS=completed
# VERSION=latest02
# END_TIME=00:27

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-01-18
begin = 2023-01-18 00:07:44.473221392+00:00
start-sync_0 = 00:22:01
start-zstd = 00:23:32
start-sync_1 = 00:26:49
end-sync_1 = 00:27:09
end = 2023-01-18 00:27:09.151639131+00:00

[server]
repo = "cake233/arch-zsh-armv7"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
start_sync = 2023-01-18 06:05:22.104903436+00:00
end_sync = 2023-01-18 06:06:19.508183803+00:00
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (GNU libc) 2.35'
zsh = 'zsh 5.9 (armv7l-unknown-linux-gnueabihf)'
