[main]
name = "arch"
tag = ["base", "2022-10-26"]
os = "arch"
release = "latest"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "arch_amd64_2022-10-26_00-05.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "c75430f0d5da12eeb68d8cd84b47af0a5c5ab01826e22b3eddf5ae8a7719d88c"

# zstd: [1-22]
zstd-level = 12

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "918M"
tar_bytes = 962383872

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "262M"
zstd_bytes = 274109926

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20211128"
previous_tag = ""
previous_file = ""
previous_sha256 = ""

current_version = "latest01"
current_date = "20221026"
old_file = ""
old_sha256 = ""
# edition 2021
# DISTRO_NAME=arch_amd64
# ROOTFS_FILE=arch_amd64_2022-10-26_00-05-rootfs.tar.zst
# SHA256SUM=c75430f0d5da12eeb68d8cd84b47af0a5c5ab01826e22b3eddf5ae8a7719d88c
# BUILD_DATE=20221026
# BUILD_TAG=2022-10-26
# STATUS=completed
# VERSION=latest01
# END_TIME=00:05

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-10-26
begin = 2022-10-26 00:02:19.669257669+00:00
start-sync_0 = 00:03:41
start-zstd = 00:04:24
start-sync_1 = 00:04:50
end-sync_1 = 00:05:12
end = 2022-10-26 00:05:12.548637691+00:00

[server]
repo = "cake233/arch-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = false
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"
