[main]
name = "arch"
tag = ["cutefish", "2022-07-20"]
os = "arch"
release = "latest"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "arch-cutefish_amd64_2022-07-20_01-20.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "c567006434c688bdfb6117e7cf45b03256dbff1ca5d86470354a7165c41c83a1"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "3.9G"
tar_bytes = 4130434560

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "1.1G"
zstd_bytes = 1172242954

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20220713"
previous_tag = "2022-07-13"
previous_file = "arch-cutefish_amd64_2022-07-13_01-02-rootfs.tar.zst"
previous_sha256 = "2d19f8aa6580f5275835887f414fc2cdc582315197d5bcb6d6136a5f8983b3f5"

current_version = "latest01"
current_date = "20220720"
old_file = "arch-cutefish_amd64_2022-07-06_00-52-rootfs.tar.zst"
old_sha256 = "54a90ded1b527900b0063ac537981d1403a96045d43468ef73c67ebe9d26828f"
# edition 2021
# DISTRO_NAME=arch_amd64
# ROOTFS_FILE=arch-cutefish_amd64_2022-07-20_01-20-rootfs.tar.zst
# SHA256SUM=c567006434c688bdfb6117e7cf45b03256dbff1ca5d86470354a7165c41c83a1
# BUILD_DATE=20220720
# BUILD_TAG=2022-07-20
# STATUS=completed
# VERSION=latest01
# END_TIME=01:20

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-07-20
begin = 2022-07-20 00:53:48.873865958+00:00
start-sync_0 = 00:59:36
start-zstd = 01:04:18
start-sync_1 = 01:19:19
end-sync_1 = 01:20:34
end = 2022-07-20 01:20:34.082444126+00:00

[server]
repo = "cake233/arch-cutefish-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = true
start_sync = 2022-11-02 06:43:46.685735911+00:00
end_sync = 2022-11-02 06:45:39.661767028+00:00
start_sync = 2022-10-26 06:44:11.387588605+00:00
end_sync = 2022-10-26 06:46:08.019658352+00:00
start_sync = 2022-10-19 06:41:34.551183252+00:00
end_sync = 2022-10-19 06:43:20.538947717+00:00
start_sync = 2022-10-12 06:41:42.924155972+00:00
end_sync = 2022-10-12 06:43:41.690110882+00:00
start_sync = 2022-10-05 06:40:52.112291368+00:00
end_sync = 2022-10-05 06:42:28.836261750+00:00
start_sync = 2022-09-28 06:41:20.632687008+00:00
end_sync = 2022-09-28 06:43:04.483797743+00:00
start_sync = 2022-09-21 06:38:59.912637279+00:00
end_sync = 2022-09-21 06:40:30.515842614+00:00
start_sync = 2022-09-14 06:41:16.940175119+00:00
end_sync = 2022-09-14 06:42:59.882243090+00:00
start_sync = 2022-09-07 06:41:50.082223541+00:00
end_sync = 2022-09-07 06:43:34.513465616+00:00
start_sync = 2022-08-31 06:42:14.703109345+00:00
end_sync = 2022-08-31 06:44:03.887488453+00:00
start_sync = 2022-08-24 06:42:57.145514662+00:00
end_sync = 2022-08-24 06:44:51.759466220+00:00
start_sync = 2022-08-17 06:46:12.873066391+00:00
end_sync = 2022-08-17 06:48:11.735132440+00:00
start_sync = 2022-08-10 06:48:15.763381269+00:00
end_sync = 2022-08-10 06:52:04.143222150+00:00
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (GNU libc) 2.35'
zsh = 'zsh 5.9 (x86_64-pc-linux-gnu)'

[port]
tcp = [5902, 36080]
