[main]
name = "arch"
tag = ["xfce", "2023-03-08"]
os = "arch"
release = "latest"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "arch-xfce_amd64_2023-03-08_00-59.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "dbbc823d80c56a84100c8f1fe3bc3a191a322cd1a31d5576899881ebb827b777"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "3.7G"
tar_bytes = 3942053888

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "1.1G"
zstd_bytes = 1161992158

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20230301"
previous_tag = "2023-03-01"
previous_file = "arch-xfce_amd64_2023-03-01_01-09-rootfs.tar.zst"
previous_sha256 = "c13dcdef05f05444d57bcd80708a9ca2fb3a69e324bdf41d575b3bf4f00847c9"

current_version = "latest01"
current_date = "20230308"
old_file = "arch-xfce_amd64_2023-02-22_01-08-rootfs.tar.zst"
old_sha256 = "280e97d8874fba84e7756829843f67b787e8a9c61d89f8e2a71eea17edc913ce"
# edition 2021
# DISTRO_NAME=arch_amd64
# ROOTFS_FILE=arch-xfce_amd64_2023-03-08_00-59-rootfs.tar.zst
# SHA256SUM=dbbc823d80c56a84100c8f1fe3bc3a191a322cd1a31d5576899881ebb827b777
# BUILD_DATE=20230308
# BUILD_TAG=2023-03-08
# STATUS=completed
# VERSION=latest01
# END_TIME=00:59

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-03-08
begin = 2023-03-08 00:30:37.034711240+00:00
start-sync_0 = 00:39:06
start-zstd = 00:43:02
start-sync_1 = 00:58:08
end-sync_1 = 00:59:24
end = 2023-03-08 00:59:24.495657832+00:00

[server]
repo = "cake233/arch-xfce-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = true
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (GNU libc) 2.37'
zsh = 'zsh 5.9 (x86_64-pc-linux-gnu)'

[port]
tcp = [5902, 36080]
