[main]
name = "euler"
tag = ["dde", "2023-03-15"]
os = "euler"
release = "dde"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = true
syntax_version = "0.0.0-alpha.4"

[file]
name = "euler-dde_amd64_2023-03-15_00-41.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "1d392b1f6e5c1ba5fcadf5984b9054a5007d535654a1935640d0755953f8888c"

# zstd: [1-22]
zstd-level = 18

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "5.2G"
tar_bytes = 5565359104

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "1.7G"
zstd_bytes = 1745847793

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20230215"
previous_tag = "2023-02-15"
previous_file = "euler-dde_amd64_2023-02-15_00-41-rootfs.tar.zst"
previous_sha256 = "43391848b7987e2febbd669a63ab4c3635f25469d4c2a2fbbfffc1310705775b"

current_version = "latest02"
current_date = "20230315"
old_file = "euler-dde_amd64_2023-01-15_00-41-rootfs.tar.zst"
old_sha256 = "15d87d4f685728598e520ac18a7e7a34c014b3af7ea150358c3ebab5ffc01827"
# edition 2021
# DISTRO_NAME=euler_amd64
# ROOTFS_FILE=euler-dde_amd64_2023-03-15_00-41-rootfs.tar.zst
# SHA256SUM=1d392b1f6e5c1ba5fcadf5984b9054a5007d535654a1935640d0755953f8888c
# BUILD_DATE=20230315
# BUILD_TAG=2023-03-15
# STATUS=completed
# VERSION=latest02
# END_TIME=00:41

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-03-15
begin = 2023-03-15 00:10:00.903463368+00:00
start-sync_0 = 00:20:51
start-zstd = 00:25:54
start-sync_1 = 00:39:39
end-sync_1 = 00:41:23
end = 2023-03-15 00:41:23.835408542+00:00

[server]
repo = "cake233/euler-dde-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = true
start_sync = 2023-10-15 04:12:09.973941581+00:00
end_sync = 2023-10-15 04:15:39.623009416+00:00
start_sync = 2023-09-15 04:13:48.797590811+00:00
end_sync = 2023-09-15 04:16:59.051882812+00:00
start_sync = 2023-08-15 04:10:01.947342181+00:00
end_sync = 2023-08-15 04:20:33.278768945+00:00
start_sync = 2023-07-15 04:10:55.562345133+00:00
end_sync = 2023-07-15 04:13:42.929484905+00:00
start_sync = 2023-06-15 04:09:58.199720129+00:00
end_sync = 2023-06-15 04:12:39.963118814+00:00
start_sync = 2023-05-15 04:11:22.581152047+00:00
end_sync = 2023-05-15 04:14:23.556400795+00:00
start_sync = 2023-04-15 04:10:06.279563551+00:00
end_sync = 2023-04-15 04:13:13.045356325+00:00
start_sync = 2023-03-15 04:11:10.204644322+00:00
end_sync = 2023-03-15 04:16:11.744638941+00:00
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[port]
tcp = [5902, 36080]
