[main]
name = "jdk"
tag = ["latest", "2022-02-07"]
os = "debian"
release = "stable"
arch = "amd64"
platform = "linux/amd64"
x11_or_wayland = false

[file]
name = "jdk_amd64_2022-02-07_12-05.tar.zst"

version = "0.0.0-alpha.2"

# This value can be used to verify the integrity of the file
sha256 = "c8af177c7ed920897676c70ffc4221f00b33e569a462081aec1084342372cb2f"

# zstd: [1-22]
zstd-level = 20

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "422M"
tar_bytes = 442030592

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "183M"
zstd_bytes = 191150058

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20220124"
previous_tag = "2022-01-24"
previous_file = "jdk_amd64_2022-01-24_12-05-rootfs.tar.zst"
previous_sha256 = "aeae6dae522c6286f129f78a48d66e489ff3eef3ad3e1495e03b09ff620448d3"

current_version = "latest02"
current_date = "20220207"
old_file = "jdk_amd64_2022-01-10_12-05-rootfs.tar.zst"
old_sha256 = "096ab8317675515c7610120d7bf379f5597b8a1c1ccf79c36834f0981ff98745"
# edition 2021
# DISTRO_NAME=jdk_amd64
# ROOTFS_FILE=jdk_amd64_2022-02-07_12-05-rootfs.tar.zst
# SHA256SUM=c8af177c7ed920897676c70ffc4221f00b33e569a462081aec1084342372cb2f
# BUILD_DATE=20220207
# BUILD_TAG=2022-02-07
# STATUS=completed
# VERSION=latest02
# END_TIME=12:05

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-02-07
begin = 2022-02-07 12:02:34.309089216+00:00
start-sync_0 = 12:03:25
start-zstd = 12:03:37
start-sync_1 = 12:05:29
end-sync_1 = 12:05:45
end = 2022-02-07 12:05:45.493469259+00:00

[server]
repo = "cake233/jdk-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = false
previous = true
in_sync = false
split = false

[server.node3]
name = "azure"
current = false
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"
PATH = "/usr/local/openjdk-19/bin${PATH:+:${PATH}}"
JAVA_HOME = '/usr/local/openjdk-19'

[version]
ldd = 'ldd (Debian GLIBC 2.31-13+deb11u2) 2.31'
java = '''
openjdk 19-ea 2022-09-20
OpenJDK Runtime Environment (build 19-ea+7-366)
OpenJDK 64-Bit Server VM (build 19-ea+7-366, mixed mode, sharing)
'''
javac = 'javac 19-ea'
