[main]
name = "amazon"
tag = ["base", "2022-12-15"]
os = "amazon"
release = "base"
arch = "amd64"
platform = "linux/amd64"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "amazon_amd64_2022-12-15_00-05.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "63898dbd426c8b9abefe1aa3b329c1408363d3a27ec118bd68c3f0c01614ba45"

# zstd: [1-22]
zstd-level = 19

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "302M"
tar_bytes = 315642368

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "52M"
zstd_bytes = 53502719

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20221115"
previous_tag = "2022-11-15"
previous_file = "amazon_amd64_2022-11-15_00-05-rootfs.tar.zst"
previous_sha256 = "066f316136f0979f3cd14d3a73b908ae1ebc0d4cce696d4a40bba149e42435c1"

current_version = "latest02"
current_date = "20221215"
old_file = "amazon_amd64_2022-10-15_00-05-rootfs.tar.zst"
old_sha256 = "f48392628c42777ea81d3c1cbfe6d01a86a420739f974119bb2511fbb159ecb0"
# edition 2021
# DISTRO_NAME=amazon_amd64
# ROOTFS_FILE=amazon_amd64_2022-12-15_00-05-rootfs.tar.zst
# SHA256SUM=63898dbd426c8b9abefe1aa3b329c1408363d3a27ec118bd68c3f0c01614ba45
# BUILD_DATE=20221215
# BUILD_TAG=2022-12-15
# STATUS=completed
# VERSION=latest02
# END_TIME=00:05

[time]
format = "rfc-3339"
zone = "UTC"
date = 2022-12-15
begin = 2022-12-15 00:03:17.122902874+00:00
start-sync_0 = 00:04:04
start-zstd = 00:04:35
start-sync_1 = 00:05:34
end-sync_1 = 00:05:45
end = 2022-12-15 00:05:45.102767220+00:00

[server]
repo = "cake233/amazon-amd64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
start_sync = 2022-12-15 04:03:42.207637088+00:00
end_sync = 2022-12-15 04:03:56.596454264+00:00
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"
