[main]
name = "code"
tag = ["latest", "2023-01-09", "vsc", "vscode", "web"]
os = "debian"
release = "sid"
arch = "arm64"
platform = "linux/arm64"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "code_arm64_2023-01-09_12-14.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "bea12e226df0afa59ab9d555abb0a6e262a9e72444590c01ae6e2a6a361657fc"

# zstd: [1-22]
zstd-level = 22

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "530M"
tar_bytes = 555712512

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "86M"
zstd_bytes = 89139671

[compatibility]
compatible_mode = true

previous_version = "latest01"

# The value is &str, not int
previous_date = "20221226"
previous_tag = "2022-12-26"
previous_file = "code_arm64_2022-12-26_12-13-rootfs.tar.zst"
previous_sha256 = "a9c5dedefc7352478f69f9b6a173c31591f8941c08bfade21b5d1146030acb42"

current_version = "latest02"
current_date = "20230109"
old_file = "code_arm64_2022-12-12_12-11-rootfs.tar.zst"
old_sha256 = "4262d09247bdca3473b87f2df5fccd8f4cdf27bfc99e2328e0d798221d748ba9"
# edition 2021
# DISTRO_NAME=code_arm64
# ROOTFS_FILE=code_arm64_2023-01-09_12-14-rootfs.tar.zst
# SHA256SUM=bea12e226df0afa59ab9d555abb0a6e262a9e72444590c01ae6e2a6a361657fc
# BUILD_DATE=20230109
# BUILD_TAG=2023-01-09
# STATUS=completed
# VERSION=latest02
# END_TIME=12:14

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-01-09
begin = 2023-01-09 12:02:33.055251372+00:00
start-sync_0 = 12:10:31
start-zstd = 12:11:06
start-sync_1 = 12:14:42
end-sync_1 = 12:14:56
end = 2023-01-09 12:14:56.051241696+00:00

[server]
repo = "cake233/code-arm64"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = false
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
start_sync = 2023-02-20 18:12:22.198220473+00:00
end_sync = 2023-02-20 18:12:38.669360531+00:00
start_sync = 2023-02-06 18:09:54.944566415+00:00
end_sync = 2023-02-06 18:10:08.240184858+00:00
start_sync = 2023-01-23 18:10:40.855197769+00:00
end_sync = 2023-01-23 18:10:55.893020656+00:00
start_sync = 2023-01-09 18:10:44.023145371+00:00
end_sync = 2023-01-09 18:11:09.220559574+00:00
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (Debian GLIBC 2.36-8) 2.36'
code = '4.9.1 f7989a4dfcf21085e52157a01924d79d708bcc05 with Code 1.73.1'

[port]
tcp = [8080]
