[main]
name = "code"
tag = ["latest", "2023-09-04", "vsc", "vscode", "web"]
os = "debian"
release = "sid"
arch = "armhf"
platform = "linux/arm/v7"
xorg_or_wayland = false
syntax_version = "0.0.0-alpha.4"

[file]
name = "code_armhf_2023-09-04_12-15.tar.zst"

# This value can be used to verify the integrity of the file
sha256 = "42568b0e6b420f39b6433282c8491e9f4e9581b468716474b2492a9a8f4f6db9"

# zstd: [1-22]
zstd-level = 22

[file.size]
# Installed size ≈ tar-size
# Installed size is approximately equal to the size of the tar file
tar = "499M"
tar_bytes = 522768384

# Space occupied ≈ tar-size + zstd-size
# You will need to prepare a large enough space before installation.
zstd = "80M"
zstd_bytes = 83072986

[compatibility]
compatible_mode = true

previous_version = "latest02"

# The value is &str, not int
previous_date = "20211128"
previous_tag = ""
previous_file = ""
previous_sha256 = ""

current_version = "latest01"
current_date = "20230904"
old_file = ""
old_sha256 = ""
# edition 2021
# DISTRO_NAME=code_armhf
# ROOTFS_FILE=code_armhf_2023-09-04_12-15-rootfs.tar.zst
# SHA256SUM=42568b0e6b420f39b6433282c8491e9f4e9581b468716474b2492a9a8f4f6db9
# BUILD_DATE=20230904
# BUILD_TAG=2023-09-04
# STATUS=completed
# VERSION=latest01
# END_TIME=12:15

[time]
format = "rfc-3339"
zone = "UTC"
date = 2023-09-04
begin = 2023-09-04 12:02:51.478994501+00:00
start-sync_0 = 12:09:57
start-zstd = 12:10:32
start-sync_1 = 12:15:04
end-sync_1 = 12:15:17
end = 2023-09-04 12:15:17.410136918+00:00

[server]
repo = "cake233/code-armv7"

[server.node1]
name = "cn"
current = false
previous = false
in_sync = false
split = false

[server.node2]
name = "tmoe"
current = true
previous = true
in_sync = false
split = false

[server.node3]
name = "azure"
current = true
previous = true
in_sync = false
split = false

[server.node4]
name = "docker"
current = true

# Environment variables  (●＞ω＜●)
[env]
LANG = "en_US.UTF-8"

[version]
ldd = 'ldd (Debian GLIBC 2.37-7) 2.37'
code = '4.16.1 94ef3776ad7bebfb5780dfc9632e04d20d5c9a6c with Code 1.80.2'

[port]
tcp = [8080]
